export function render_generated_module_docstring(
  summary: string,
  _generated_at: string,
  details: string[] = [],
): string {
  const lines = [`"""${summary}`, ""];
  if (details.length > 0) {
    lines.push(...details, "");
  }
  lines.push("Generated by html-codegen.", '"""');
  return lines.join("\n");
}
