import React from "react";
import { useBreadcrumbs } from "react-aria";
import { colors, spacing, typography } from "../theme";
import { Icon } from "./Icon";

interface BreadcrumbContainerProps {
  separator?: string;
  className?: string;
  style?: React.CSSProperties;
  children?: React.ReactNode;
}

// Unique ID for scoping breadcrumb styles
let breadcrumbIdCounter = 0;

/**
 * BreadcrumbContainer - Renders children with separators between them.
 *
 * Children are native Trellis elements (A for links, Label for current page)
 * generated by the Python Breadcrumb composition component.
 */
export function BreadcrumbContainer({
  separator = "/",
  className,
  style,
  children,
}: BreadcrumbContainerProps): React.ReactElement {
  const { navProps } = useBreadcrumbs({});
  const childArray = React.Children.toArray(children);
  const scopeId = React.useMemo(() => `breadcrumb-${++breadcrumbIdCounter}`, []);

  return (
    <nav
      {...navProps}
      className={`${scopeId} ${className || ""}`.trim()}
      style={{
        display: "flex",
        alignItems: "center",
        fontFamily: typography.fontFamily,
        fontSize: typography.fontSize.sm,
        lineHeight: 1.5,
        ...style,
      }}
    >
      {/* Scoped styles for anchor elements within this breadcrumb */}
      <style>
        {`
          .${scopeId} a {
            color: ${colors.text.secondary};
            text-decoration: none;
            cursor: pointer;
            transition: color 0.15s ease;
          }
          .${scopeId} a:hover {
            color: ${colors.accent.primary};
          }
        `}
      </style>
      <ol
        style={{
          display: "flex",
          alignItems: "center",
          gap: spacing.xs,
          listStyle: "none",
          margin: 0,
          padding: 0,
        }}
      >
        {childArray.map((child, index) => (
          <li
            key={index}
            style={{
              display: "flex",
              alignItems: "center",
              gap: spacing.xs,
            }}
          >
            {index > 0 && (
              <span
                aria-hidden="true"
                style={{
                  color: colors.text.muted,
                  userSelect: "none",
                  display: "flex",
                  alignItems: "center",
                }}
              >
                {separator === "/" ? (
                  <Icon name="chevron-right" size={14} color={colors.text.muted} />
                ) : (
                  separator
                )}
              </span>
            )}
            <BreadcrumbItem isLast={index === childArray.length - 1}>
              {child}
            </BreadcrumbItem>
          </li>
        ))}
      </ol>
    </nav>
  );
}

/**
 * BreadcrumbItem - Wrapper that applies styling to each breadcrumb child.
 *
 * Applies different styles for current (last) item vs navigable items.
 * Anchor styling is handled by scoped CSS in the parent BreadcrumbContainer.
 * The actual content (A element or Label) is passed as children from Python.
 */
function BreadcrumbItem({
  isLast,
  children,
}: {
  isLast: boolean;
  children: React.ReactNode;
}): React.ReactElement {
  return (
    <span
      style={{
        // Current page styling (last item)
        ...(isLast
          ? {
              color: colors.text.primary,
              fontWeight: typography.fontWeight.medium,
            }
          : {}),
      }}
    >
      {children}
    </span>
  );
}

// Legacy export for backwards compatibility during migration
// TODO: Remove after all usages are migrated to container pattern
interface LegacyBreadcrumbItem {
  label: string;
  href?: string;
}

interface LegacyBreadcrumbProps {
  items?: LegacyBreadcrumbItem[];
  separator?: string;
  on_click?: (index: number) => void;
  className?: string;
  style?: React.CSSProperties;
}

export function Breadcrumb({
  items = [],
  separator = "/",
  on_click,
  className,
  style,
}: LegacyBreadcrumbProps): React.ReactElement {
  const { navProps } = useBreadcrumbs({});

  const isLast = (index: number) => index === items.length - 1;

  return (
    <nav
      {...navProps}
      className={className}
      style={{
        display: "flex",
        alignItems: "center",
        gap: spacing.sm,
        fontFamily: typography.fontFamily,
        fontSize: typography.fontSize.sm,
        ...style,
      }}
    >
      <ol
        style={{
          display: "flex",
          alignItems: "center",
          gap: spacing.sm,
          listStyle: "none",
          margin: 0,
          padding: 0,
        }}
      >
        {items.map((item, index) => (
          <li
            key={index}
            style={{ display: "flex", alignItems: "center", gap: spacing.sm }}
          >
            {index > 0 && (
              <span
                aria-hidden="true"
                style={{
                  color: colors.text.muted,
                  userSelect: "none",
                }}
              >
                {separator === "/" ? (
                  <Icon name="chevron-right" size={14} color={colors.text.muted} />
                ) : (
                  separator
                )}
              </span>
            )}
            <LegacyBreadcrumbLink
              item={item}
              index={index}
              isLast={isLast(index)}
              on_click={on_click}
            />
          </li>
        ))}
      </ol>
    </nav>
  );
}

function LegacyBreadcrumbLink({
  item,
  index,
  isLast,
  on_click,
}: {
  item: LegacyBreadcrumbItem;
  index: number;
  isLast: boolean;
  on_click?: (index: number) => void;
}) {
  const [isHovered, setIsHovered] = React.useState(false);

  const handleClick = (e: React.MouseEvent) => {
    if (on_click && !isLast) {
      e.preventDefault();
      on_click(index);
    }
  };

  if (isLast) {
    return (
      <span
        style={{
          color: colors.text.primary,
          fontWeight: typography.fontWeight.medium,
        }}
      >
        {item.label}
      </span>
    );
  }

  return (
    <a
      href={item.href || "#"}
      onClick={handleClick}
      style={{
        color: isHovered ? colors.accent.primary : colors.text.secondary,
        textDecoration: "none",
        cursor: "pointer",
        transition: "color 0.15s ease",
      }}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      {item.label}
    </a>
  );
}
