"""Core rendering primitives for the Trellis UI framework."""

# components
from trellis.core.components import (
    Component,
    CompositionComponent,
    ReactComponentBase,
    component,
    react,
)

# keys
from trellis.core.keys import KeyFilter, KeySequence, parse_key_filter, sequence

# state
from trellis.core.protocol import (
    Message,
    MessageHandler,
    MessageHandlerProtocol,
    StatefulMessageHandlerMixin,
    dispatch,
    get_message_handler,
    listen,
    register_message_types,
    send,
    set_message_handler,
)

# rendering
from trellis.core.rendering import (
    ActiveRender,
    ContainerElement,
    ContainerTrait,
    DirtyTracker,
    Element,
    ElementState,
    ElementStateStore,
    ElementStore,
    Frame,
    FrameStack,
    KeyTrait,
    LifecycleTracker,
    PatchCollector,
    RenderAddPatch,
    RenderPatch,
    RenderRemovePatch,
    RenderSession,
    RenderUpdatePatch,
    get_render_session,
    is_render_active,
    props_equal,
    reconcile_children,
    render,
    set_render_session,
)
from trellis.core.state import (
    Mutable,
    Ref,
    Stateful,
    Tracked,
    TrackedDict,
    TrackedList,
    TrackedSet,
    callback,
    convert_to_tracked,
    get_ref,
    mutable,
    set_ref,
)

__all__ = [
    "ActiveRender",
    "Component",
    "CompositionComponent",
    "ContainerElement",
    "ContainerTrait",
    "DirtyTracker",
    "Element",
    "ElementState",
    "ElementStateStore",
    "ElementStore",
    "Frame",
    "FrameStack",
    "Height",
    "KeyFilter",
    "KeySequence",
    "KeyTrait",
    "LifecycleTracker",
    "Message",
    "MessageHandler",
    "MessageHandlerProtocol",
    "Mutable",
    "PatchCollector",
    "ReactComponentBase",
    "Ref",
    "RenderAddPatch",
    "RenderPatch",
    "RenderRemovePatch",
    "RenderSession",
    "RenderUpdatePatch",
    "Stateful",
    "StatefulMessageHandlerMixin",
    "Tracked",
    "TrackedDict",
    "TrackedList",
    "TrackedSet",
    "callback",
    "component",
    "convert_to_tracked",
    "dispatch",
    "get_message_handler",
    "get_ref",
    "get_render_session",
    "is_render_active",
    "listen",
    "mutable",
    "parse_key_filter",
    "props_equal",
    "react",
    "reconcile_children",
    "register_message_types",
    "render",
    "send",
    "sequence",
    "set_message_handler",
    "set_ref",
    "set_render_session",
]
