"""Core rendering primitives for the Trellis UI framework."""

# components
from trellis.core.components import (
    Component,
    CompositionComponent,
    Height,
    Margin,
    Padding,
    ReactComponentBase,
    Width,
    component,
    react,
)

# rendering
from trellis.core.rendering import (
    ActiveRender,
    DirtyTracker,
    Element,
    ElementState,
    ElementStateStore,
    ElementStore,
    Frame,
    FrameStack,
    KeyTrait,
    LifecycleTracker,
    PatchCollector,
    RenderAddPatch,
    RenderPatch,
    RenderRemovePatch,
    RenderSession,
    RenderUpdatePatch,
    get_active_session,
    is_render_active,
    props_equal,
    reconcile_children,
    render,
    set_active_session,
)

# state
from trellis.core.state import (
    Mutable,
    Stateful,
    TrackedDict,
    TrackedList,
    TrackedSet,
    callback,
    convert_to_tracked,
    mutable,
)

__all__ = [
    "ActiveRender",
    "Component",
    "CompositionComponent",
    "DirtyTracker",
    "Element",
    "ElementState",
    "ElementStateStore",
    "ElementStore",
    "Frame",
    "FrameStack",
    "Height",
    "KeyTrait",
    "LifecycleTracker",
    "Margin",
    "Mutable",
    "Padding",
    "PatchCollector",
    "ReactComponentBase",
    "RenderAddPatch",
    "RenderPatch",
    "RenderRemovePatch",
    "RenderSession",
    "RenderUpdatePatch",
    "Stateful",
    "TrackedDict",
    "TrackedList",
    "TrackedSet",
    "Width",
    "callback",
    "component",
    "convert_to_tracked",
    "get_active_session",
    "is_render_active",
    "mutable",
    "props_equal",
    "react",
    "reconcile_children",
    "render",
    "set_active_session",
]
