/**
 * Standalone entry point for browser platform.
 *
 * This is used when generating self-contained HTML deployments.
 * Configuration is read from window.__TRELLIS_CONFIG__.
 *
 * When SSR data is present (window.__TRELLIS_SSR__), the store is
 * pre-populated and hydrateRoot is used so the pre-rendered HTML
 * becomes interactive without a flash of empty content.
 */

// Initialize widget registry before any rendering
import { initRegistry } from "@trellis/_registry";
initRegistry();

import "@trellis/trellis-core/theme.css"; // Theme CSS variables
import "@trellis/trellis-core/console"; // Set up console filtering
import React from "react";
import { createRoot, hydrateRoot } from "react-dom/client";
import { TrellisApp, RoutingMode } from "@trellis/trellis-browser/client/src/TrellisApp";
import { store } from "@trellis/trellis-core/core";
import type { Patch } from "@trellis/trellis-core/types";

interface TrellisSSRData {
  serverVersion: string;
  patches: Patch[];
}

declare global {
  interface Window {
    __TRELLIS_CONFIG__?: {
      routingMode?: string;
    };
    __TRELLIS_SSR__?: TrellisSSRData;
  }
}

const ssrData = window.__TRELLIS_SSR__;

function App() {
  const config = window.__TRELLIS_CONFIG__;

  if (!config) {
    return (
      <div
        style={{
          padding: "20px",
          color: "#dc2626",
          fontFamily: "system-ui",
        }}
      >
        <h2>Configuration Error</h2>
        <p>
          Missing <code>window.__TRELLIS_CONFIG__</code>. This page should be
          generated by <code>trellis bundle --platform browser</code> or
          served by <code>trellis run --browser</code>.
        </p>
      </div>
    );
  }

  // Parse routing mode from config string
  const routingMode = config.routingMode as RoutingMode | undefined;

  return (
    <TrellisApp routingMode={routingMode} hydrated={!!ssrData} />
  );
}

const container = document.getElementById("root")!;

if (ssrData) {
  // SSR path: pre-populate the store with build-time patches,
  // then hydrate the existing DOM.
  store.applyPatches(ssrData.patches);
  hydrateRoot(container, <App />);
} else {
  // CSR path: create a fresh root.
  const root = createRoot(container);
  root.render(<App />);
}
