/**
 * Standalone entry point for browser platform.
 *
 * This is used when generating self-contained HTML deployments.
 * Configuration is read from window.__TRELLIS_CONFIG__.
 */

import "../../../common/client/src/theme.css"; // Theme CSS variables
import "../../../common/client/src/console"; // Set up console filtering
import React from "react";
import { createRoot } from "react-dom/client";
import { TrellisApp, PythonSource } from "./TrellisApp";

declare global {
  interface Window {
    __TRELLIS_CONFIG__?: {
      source: PythonSource;
      main?: string;
      workerUrl: string;
      trellisWheelUrl?: string;
    };
  }
}

function App() {
  const config = window.__TRELLIS_CONFIG__;

  if (!config) {
    return (
      <div
        style={{
          padding: "20px",
          color: "#dc2626",
          fontFamily: "system-ui",
        }}
      >
        <h2>Configuration Error</h2>
        <p>
          Missing <code>window.__TRELLIS_CONFIG__</code>. This page should be
          generated by <code>trellis bundle build --platform browser</code> or
          served by <code>python app.py --browser</code>.
        </p>
      </div>
    );
  }

  return (
    <TrellisApp
      source={config.source}
      main={config.main}
      workerUrl={config.workerUrl}
      trellisWheelUrl={config.trellisWheelUrl}
    />
  );
}

const container = document.getElementById("root");
if (container) {
  const root = createRoot(container);
  root.render(<App />);
}
