/**
 * Standalone entry point for browser platform.
 *
 * This is used when generating self-contained HTML deployments.
 * Configuration is read from window.__TRELLIS_CONFIG__.
 */

// Initialize widget registry before any rendering
import { initRegistry } from "@trellis/_registry";
initRegistry();

import "@trellis/trellis-core/client/src/theme.css"; // Theme CSS variables
import "@trellis/trellis-core/client/src/console"; // Set up console filtering
import React from "react";
import { createRoot } from "react-dom/client";
import { TrellisApp, RoutingMode } from "@trellis/trellis-browser/client/src/TrellisApp";

declare global {
  interface Window {
    __TRELLIS_CONFIG__?: {
      routingMode?: string;
    };
  }
}

function App() {
  const config = window.__TRELLIS_CONFIG__;

  if (!config) {
    return (
      <div
        style={{
          padding: "20px",
          color: "#dc2626",
          fontFamily: "system-ui",
        }}
      >
        <h2>Configuration Error</h2>
        <p>
          Missing <code>window.__TRELLIS_CONFIG__</code>. This page should be
          generated by <code>trellis bundle --platform browser</code> or
          served by <code>trellis run --browser</code>.
        </p>
      </div>
    );
  }

  // Parse routing mode from config string
  const routingMode = config.routingMode as RoutingMode | undefined;

  return (
    <TrellisApp routingMode={routingMode} />
  );
}

const container = document.getElementById("root");
if (container) {
  const root = createRoot(container);
  root.render(<App />);
}
