"""Native HTML element wrappers for Trellis.

Provides Python wrappers for common HTML elements that render directly
as native DOM elements in React, without requiring separate React components.

Example:
    ```python
    from trellis import html as h

    with h.Div(class_name="container", style={"padding": "16px"}):
        h.H1("Welcome", style={"color": "blue"})
        h.P("This is a paragraph.")
        h.A("Click here", href="/about")
    ```

Categories:
    - Layout: Div, Span, Section, Article, Header, Footer, Nav, Main, Aside,
              Blockquote, Address, Details, Summary, Figure, Figcaption
    - Text: P, H1-H6, Strong, Em, Code, Pre, Br, Hr, Small, Mark, Sub, Sup,
            Abbr, Time
    - Lists: Ul, Ol, Li, Dl, Dt, Dd
    - Links: A, Img
    - Forms: Form, Input, Button, Textarea, Select, Option, Label,
             Fieldset, Legend, Optgroup, Progress, Meter, Output, Datalist
    - Tables: Table, Thead, Tbody, Tfoot, Tr, Th, Td, Caption
    - Media: Video, Audio, Source, Iframe
"""

# Base types
# Generated HTML elements
# Event types
from trellis.html._generated_events import (
    DataTransfer,
    DragEvent,
    DragEventHandler,
    Event,
    EventHandler,
    File,
    FocusEvent,
    FocusEventHandler,
    InputEvent,
    InputEventHandler,
    KeyboardEvent,
    KeyboardEventHandler,
    MouseEvent,
    MouseEventHandler,
    SubmitEvent,
    SubmitEventHandler,
    UIEvent,
    UIEventHandler,
    WheelEvent,
    WheelEventHandler,
)
from trellis.html._generated_runtime import (
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    Abbr,
    Address,
    Article,
    Aside,
    Audio,
    Blockquote,
    Br,
    Button,
    Caption,
    Code,
    Datalist,
    Dd,
    Details,
    Div,
    Dl,
    Dt,
    Em,
    Fieldset,
    Figcaption,
    Figure,
    Footer,
    Form,
    Header,
    Hr,
    Iframe,
    Img,
    Input,
    Label,
    Legend,
    Li,
    Main,
    Mark,
    Meter,
    Nav,
    Ol,
    Optgroup,
    Option,
    Output,
    P,
    Pre,
    Progress,
    Section,
    Select,
    Small,
    Source,
    Span,
    Strong,
    Sub,
    Summary,
    Sup,
    Table,
    Tbody,
    Td,
    Textarea,
    Tfoot,
    Th,
    Thead,
    Time,
    Tr,
    Ul,
    Video,
)
from trellis.html.base import HtmlContainerTrait, HtmlElement, Style
from trellis.html.links import A
from trellis.html.text import Text

__all__ = [
    "H1",
    "H2",
    "H3",
    "H4",
    "H5",
    "H6",
    "A",
    "Abbr",
    "Address",
    "Article",
    "Aside",
    "Audio",
    "Blockquote",
    "Br",
    "Button",
    "Caption",
    "Code",
    "DataTransfer",
    "Datalist",
    "Dd",
    "Details",
    "Div",
    "Dl",
    "DragEvent",
    "DragEventHandler",
    "Dt",
    "Em",
    "Event",
    "EventHandler",
    "Fieldset",
    "Figcaption",
    "Figure",
    "File",
    "FocusEvent",
    "FocusEventHandler",
    "Footer",
    "Form",
    "Header",
    "Hr",
    "HtmlContainerTrait",
    "HtmlElement",
    "Iframe",
    "Img",
    "Input",
    "InputEvent",
    "InputEventHandler",
    "KeyboardEvent",
    "KeyboardEventHandler",
    "Label",
    "Legend",
    "Li",
    "Main",
    "Mark",
    "Meter",
    "MouseEvent",
    "MouseEventHandler",
    "Nav",
    "Ol",
    "Optgroup",
    "Option",
    "Output",
    "P",
    "Pre",
    "Progress",
    "Section",
    "Select",
    "Small",
    "Source",
    "Span",
    "Strong",
    "Style",
    "Sub",
    "SubmitEvent",
    "SubmitEventHandler",
    "Summary",
    "Sup",
    "Table",
    "Tbody",
    "Td",
    "Text",
    "Textarea",
    "Tfoot",
    "Th",
    "Thead",
    "Time",
    "Tr",
    "UIEvent",
    "UIEventHandler",
    "Ul",
    "Video",
    "WheelEvent",
    "WheelEventHandler",
]
