"""Generated HTML text blocks runtime wrappers.

Internal codegen artifact for trellis.html.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements

Generated by html-codegen.
"""

from __future__ import annotations

from trellis.html._runtime_factory import create_html_element

__all__ = [
    "H1",
    "H2",
    "H3",
    "H4",
    "H5",
    "H6",
    "Blockquote",
    "P",
    "Pre",
]

Blockquote = create_html_element(
    "blockquote",
    component_name="Blockquote",
    export_name="Blockquote",
    is_container=True,
    doc="Generated wrapper for `<blockquote>`.\n\nMaps to the standard HTML `<blockquote>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote",
)
H1 = create_html_element(
    "h1",
    component_name="H1",
    export_name="H1",
    is_container=True,
    doc="Generated wrapper for `<h1>`.\n\nMaps to the standard HTML `<h1>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/h1",
)
H2 = create_html_element(
    "h2",
    component_name="H2",
    export_name="H2",
    is_container=True,
    doc="Generated wrapper for `<h2>`.\n\nMaps to the standard HTML `<h2>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/h2",
)
H3 = create_html_element(
    "h3",
    component_name="H3",
    export_name="H3",
    is_container=True,
    doc="Generated wrapper for `<h3>`.\n\nMaps to the standard HTML `<h3>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/h3",
)
H4 = create_html_element(
    "h4",
    component_name="H4",
    export_name="H4",
    is_container=True,
    doc="Generated wrapper for `<h4>`.\n\nMaps to the standard HTML `<h4>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/h4",
)
H5 = create_html_element(
    "h5",
    component_name="H5",
    export_name="H5",
    is_container=True,
    doc="Generated wrapper for `<h5>`.\n\nMaps to the standard HTML `<h5>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/h5",
)
H6 = create_html_element(
    "h6",
    component_name="H6",
    export_name="H6",
    is_container=True,
    doc="Generated wrapper for `<h6>`.\n\nMaps to the standard HTML `<h6>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/h6",
)
P = create_html_element(
    "p",
    component_name="P",
    export_name="P",
    is_container=True,
    doc="Generated wrapper for `<p>`.\n\nMaps to the standard HTML `<p>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p",
)
Pre = create_html_element(
    "pre",
    component_name="Pre",
    export_name="Pre",
    is_container=True,
    doc="Generated wrapper for `<pre>`.\n\nMaps to the standard HTML `<pre>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre",
)
