"""Generated HTML image and multimedia elements.

Generated at: 2026-03-07T21:02:13.251Z
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Literal

from trellis.core.rendering.element import Element
from trellis.html.base import HtmlContainerElement, Style, html_element
from trellis.html.events import (
    DragEventHandler,
    EventHandler,
    FocusEventHandler,
    InputEventHandler,
    KeyboardEventHandler,
    MouseEventHandler,
    SubmitEventHandler,
    UIEventHandler,
    WheelEventHandler,
)

__all__ = [
    "Area",
    "Audio",
    "Img",
    "Map",
    "Picture",
    "Source",
    "Track",
    "Video",
]

DataValue = str | int | float | bool | None


@html_element("area")
def Area(
    *,
    about: str | None = None,
    access_key: str | None = None,
    alt: str | None = None,
    aria_activedescendant: str | None = None,
    aria_atomic: bool | None = None,
    aria_autocomplete: Literal["none", "inline", "list", "both"] | None = None,
    aria_braillelabel: str | None = None,
    aria_brailleroledescription: str | None = None,
    aria_busy: bool | None = None,
    aria_checked: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_colcount: int | float | None = None,
    aria_colindex: int | float | None = None,
    aria_colindextext: str | None = None,
    aria_colspan: int | float | None = None,
    aria_controls: str | None = None,
    aria_current: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["page"]
        | Literal["step"]
        | Literal["location"]
        | Literal["date"]
        | Literal["time"]
        | None
    ) = None,
    aria_describedby: str | None = None,
    aria_description: str | None = None,
    aria_details: str | None = None,
    aria_disabled: bool | None = None,
    aria_dropeffect: (
        Literal[
            "none",
            "copy",
            "execute",
            "link",
            "move",
            "popup",
        ]
        | None
    ) = None,
    aria_errormessage: str | None = None,
    aria_expanded: bool | None = None,
    aria_flowto: str | None = None,
    aria_grabbed: bool | None = None,
    aria_haspopup: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["menu"]
        | Literal["listbox"]
        | Literal["tree"]
        | Literal["grid"]
        | Literal["dialog"]
        | None
    ) = None,
    aria_hidden: bool | None = None,
    aria_invalid: (
        bool | Literal["false"] | Literal["true"] | Literal["grammar"] | Literal["spelling"] | None
    ) = None,
    aria_keyshortcuts: str | None = None,
    aria_label: str | None = None,
    aria_labelledby: str | None = None,
    aria_level: int | float | None = None,
    aria_live: Literal["off", "assertive", "polite"] | None = None,
    aria_modal: bool | None = None,
    aria_multiline: bool | None = None,
    aria_multiselectable: bool | None = None,
    aria_orientation: Literal["horizontal", "vertical"] | None = None,
    aria_owns: str | None = None,
    aria_placeholder: str | None = None,
    aria_posinset: int | float | None = None,
    aria_pressed: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_readonly: bool | None = None,
    aria_relevant: (
        Literal[
            "additions",
            "additions removals",
            "additions text",
            "all",
            "removals",
            "removals additions",
            "removals text",
            "text",
            "text additions",
            "text removals",
        ]
        | None
    ) = None,
    aria_required: bool | None = None,
    aria_roledescription: str | None = None,
    aria_rowcount: int | float | None = None,
    aria_rowindex: int | float | None = None,
    aria_rowindextext: str | None = None,
    aria_rowspan: int | float | None = None,
    aria_selected: bool | None = None,
    aria_setsize: int | float | None = None,
    aria_sort: Literal["none", "ascending", "descending", "other"] | None = None,
    aria_valuemax: int | float | None = None,
    aria_valuemin: int | float | None = None,
    aria_valuenow: int | float | None = None,
    aria_valuetext: str | None = None,
    auto_capitalize: (
        Literal[
            "off",
            "none",
            "on",
            "sentences",
            "words",
            "characters",
        ]
        | None
    ) = None,
    auto_correct: str | None = None,
    auto_focus: bool | None = None,
    auto_save: str | None = None,
    class_name: str | None = None,
    color: str | None = None,
    content: str | None = None,
    content_editable: bool | Literal["inherit"] | Literal["plaintext-only"] | None = None,
    context_menu: str | None = None,
    coords: str | None = None,
    datatype: str | None = None,
    default_checked: bool | None = None,
    default_value: str | int | float | list[str] | None = None,
    dir: str | None = None,
    download: str | bool | None = None,
    draggable: bool | None = None,
    enter_key_hint: (
        Literal[
            "enter",
            "done",
            "go",
            "next",
            "previous",
            "search",
            "send",
        ]
        | None
    ) = None,
    exportparts: str | None = None,
    hidden: bool | None = None,
    href: str | None = None,
    href_lang: str | None = None,
    id: str | None = None,
    inert: bool | None = None,
    inlist: str | None = None,
    input_mode: (
        Literal[
            "none",
            "text",
            "tel",
            "url",
            "email",
            "numeric",
            "decimal",
            "search",
        ]
        | None
    ) = None,
    is_: str | None = None,
    item_id: str | None = None,
    item_prop: str | None = None,
    item_ref: str | None = None,
    item_scope: bool | None = None,
    item_type: str | None = None,
    lang: str | None = None,
    media: str | None = None,
    nonce: str | None = None,
    part: str | None = None,
    popover: Literal["", "auto", "manual", "hint"] | None = None,
    popover_target: str | None = None,
    popover_target_action: Literal["toggle", "show", "hide"] | None = None,
    prefix: str | None = None,
    property: str | None = None,
    radio_group: str | None = None,
    referrer_policy: (
        Literal[
            "",
            "no-referrer",
            "no-referrer-when-downgrade",
            "origin",
            "origin-when-cross-origin",
            "same-origin",
            "strict-origin",
            "strict-origin-when-cross-origin",
            "unsafe-url",
        ]
        | None
    ) = None,
    rel: str | None = None,
    resource: str | None = None,
    results: int | float | None = None,
    rev: str | None = None,
    role: (
        Literal[
            "alert",
            "alertdialog",
            "application",
            "article",
            "banner",
            "button",
            "cell",
            "checkbox",
            "columnheader",
            "combobox",
            "complementary",
            "contentinfo",
            "definition",
            "dialog",
            "directory",
            "document",
            "feed",
            "figure",
            "form",
            "grid",
            "gridcell",
            "group",
            "heading",
            "img",
            "link",
            "list",
            "listbox",
            "listitem",
            "log",
            "main",
            "marquee",
            "math",
            "menu",
            "menubar",
            "menuitem",
            "menuitemcheckbox",
            "menuitemradio",
            "navigation",
            "none",
            "note",
            "option",
            "presentation",
            "progressbar",
            "radio",
            "radiogroup",
            "region",
            "row",
            "rowgroup",
            "rowheader",
            "scrollbar",
            "search",
            "searchbox",
            "separator",
            "slider",
            "spinbutton",
            "status",
            "switch",
            "tab",
            "table",
            "tablist",
            "tabpanel",
            "term",
            "textbox",
            "timer",
            "toolbar",
            "tooltip",
            "tree",
            "treegrid",
            "treeitem",
        ]
        | None
    ) = None,
    security: str | None = None,
    shape: str | None = None,
    slot: str | None = None,
    spell_check: bool | None = None,
    style: Style | None = None,
    suppress_content_editable_warning: bool | None = None,
    suppress_hydration_warning: bool | None = None,
    tab_index: int | float | None = None,
    target: str | None = None,
    title: str | None = None,
    translate: Literal["yes", "no"] | None = None,
    typeof: str | None = None,
    unselectable: Literal["on", "off"] | None = None,
    vocab: str | None = None,
    on_blur: FocusEventHandler | None = None,
    on_change: EventHandler | None = None,
    on_click: MouseEventHandler | None = None,
    on_context_menu: MouseEventHandler | None = None,
    on_double_click: MouseEventHandler | None = None,
    on_drag: DragEventHandler | None = None,
    on_drag_end: DragEventHandler | None = None,
    on_drag_enter: DragEventHandler | None = None,
    on_drag_leave: DragEventHandler | None = None,
    on_drag_over: DragEventHandler | None = None,
    on_drag_start: DragEventHandler | None = None,
    on_drop: DragEventHandler | None = None,
    on_focus: FocusEventHandler | None = None,
    on_input: InputEventHandler | None = None,
    on_key_down: KeyboardEventHandler | None = None,
    on_key_up: KeyboardEventHandler | None = None,
    on_mouse_down: MouseEventHandler | None = None,
    on_mouse_enter: MouseEventHandler | None = None,
    on_mouse_leave: MouseEventHandler | None = None,
    on_mouse_move: MouseEventHandler | None = None,
    on_mouse_out: MouseEventHandler | None = None,
    on_mouse_over: MouseEventHandler | None = None,
    on_mouse_up: MouseEventHandler | None = None,
    on_scroll: UIEventHandler | None = None,
    on_submit: SubmitEventHandler | None = None,
    on_wheel: WheelEventHandler | None = None,
    data: Mapping[str, DataValue] | None = None,
) -> Element:
    """<area />"""
    ...


@html_element("audio", is_container=True)
def Audio(
    *,
    about: str | None = None,
    access_key: str | None = None,
    aria_activedescendant: str | None = None,
    aria_atomic: bool | None = None,
    aria_autocomplete: Literal["none", "inline", "list", "both"] | None = None,
    aria_braillelabel: str | None = None,
    aria_brailleroledescription: str | None = None,
    aria_busy: bool | None = None,
    aria_checked: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_colcount: int | float | None = None,
    aria_colindex: int | float | None = None,
    aria_colindextext: str | None = None,
    aria_colspan: int | float | None = None,
    aria_controls: str | None = None,
    aria_current: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["page"]
        | Literal["step"]
        | Literal["location"]
        | Literal["date"]
        | Literal["time"]
        | None
    ) = None,
    aria_describedby: str | None = None,
    aria_description: str | None = None,
    aria_details: str | None = None,
    aria_disabled: bool | None = None,
    aria_dropeffect: (
        Literal[
            "none",
            "copy",
            "execute",
            "link",
            "move",
            "popup",
        ]
        | None
    ) = None,
    aria_errormessage: str | None = None,
    aria_expanded: bool | None = None,
    aria_flowto: str | None = None,
    aria_grabbed: bool | None = None,
    aria_haspopup: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["menu"]
        | Literal["listbox"]
        | Literal["tree"]
        | Literal["grid"]
        | Literal["dialog"]
        | None
    ) = None,
    aria_hidden: bool | None = None,
    aria_invalid: (
        bool | Literal["false"] | Literal["true"] | Literal["grammar"] | Literal["spelling"] | None
    ) = None,
    aria_keyshortcuts: str | None = None,
    aria_label: str | None = None,
    aria_labelledby: str | None = None,
    aria_level: int | float | None = None,
    aria_live: Literal["off", "assertive", "polite"] | None = None,
    aria_modal: bool | None = None,
    aria_multiline: bool | None = None,
    aria_multiselectable: bool | None = None,
    aria_orientation: Literal["horizontal", "vertical"] | None = None,
    aria_owns: str | None = None,
    aria_placeholder: str | None = None,
    aria_posinset: int | float | None = None,
    aria_pressed: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_readonly: bool | None = None,
    aria_relevant: (
        Literal[
            "additions",
            "additions removals",
            "additions text",
            "all",
            "removals",
            "removals additions",
            "removals text",
            "text",
            "text additions",
            "text removals",
        ]
        | None
    ) = None,
    aria_required: bool | None = None,
    aria_roledescription: str | None = None,
    aria_rowcount: int | float | None = None,
    aria_rowindex: int | float | None = None,
    aria_rowindextext: str | None = None,
    aria_rowspan: int | float | None = None,
    aria_selected: bool | None = None,
    aria_setsize: int | float | None = None,
    aria_sort: Literal["none", "ascending", "descending", "other"] | None = None,
    aria_valuemax: int | float | None = None,
    aria_valuemin: int | float | None = None,
    aria_valuenow: int | float | None = None,
    aria_valuetext: str | None = None,
    auto_capitalize: (
        Literal[
            "off",
            "none",
            "on",
            "sentences",
            "words",
            "characters",
        ]
        | None
    ) = None,
    auto_correct: str | None = None,
    auto_focus: bool | None = None,
    auto_play: bool | None = None,
    auto_save: str | None = None,
    class_name: str | None = None,
    color: str | None = None,
    content: str | None = None,
    content_editable: bool | Literal["inherit"] | Literal["plaintext-only"] | None = None,
    context_menu: str | None = None,
    controls: bool | None = None,
    controls_list: str | None = None,
    cross_origin: Literal["anonymous", "use-credentials", ""] | None = None,
    datatype: str | None = None,
    default_checked: bool | None = None,
    default_value: str | int | float | list[str] | None = None,
    dir: str | None = None,
    draggable: bool | None = None,
    enter_key_hint: (
        Literal[
            "enter",
            "done",
            "go",
            "next",
            "previous",
            "search",
            "send",
        ]
        | None
    ) = None,
    exportparts: str | None = None,
    hidden: bool | None = None,
    id: str | None = None,
    inert: bool | None = None,
    inlist: str | None = None,
    input_mode: (
        Literal[
            "none",
            "text",
            "tel",
            "url",
            "email",
            "numeric",
            "decimal",
            "search",
        ]
        | None
    ) = None,
    is_: str | None = None,
    item_id: str | None = None,
    item_prop: str | None = None,
    item_ref: str | None = None,
    item_scope: bool | None = None,
    item_type: str | None = None,
    lang: str | None = None,
    loop: bool | None = None,
    media_group: str | None = None,
    muted: bool | None = None,
    nonce: str | None = None,
    part: str | None = None,
    plays_inline: bool | None = None,
    popover: Literal["", "auto", "manual", "hint"] | None = None,
    popover_target: str | None = None,
    popover_target_action: Literal["toggle", "show", "hide"] | None = None,
    prefix: str | None = None,
    preload: str | None = None,
    property: str | None = None,
    radio_group: str | None = None,
    rel: str | None = None,
    resource: str | None = None,
    results: int | float | None = None,
    rev: str | None = None,
    role: (
        Literal[
            "alert",
            "alertdialog",
            "application",
            "article",
            "banner",
            "button",
            "cell",
            "checkbox",
            "columnheader",
            "combobox",
            "complementary",
            "contentinfo",
            "definition",
            "dialog",
            "directory",
            "document",
            "feed",
            "figure",
            "form",
            "grid",
            "gridcell",
            "group",
            "heading",
            "img",
            "link",
            "list",
            "listbox",
            "listitem",
            "log",
            "main",
            "marquee",
            "math",
            "menu",
            "menubar",
            "menuitem",
            "menuitemcheckbox",
            "menuitemradio",
            "navigation",
            "none",
            "note",
            "option",
            "presentation",
            "progressbar",
            "radio",
            "radiogroup",
            "region",
            "row",
            "rowgroup",
            "rowheader",
            "scrollbar",
            "search",
            "searchbox",
            "separator",
            "slider",
            "spinbutton",
            "status",
            "switch",
            "tab",
            "table",
            "tablist",
            "tabpanel",
            "term",
            "textbox",
            "timer",
            "toolbar",
            "tooltip",
            "tree",
            "treegrid",
            "treeitem",
        ]
        | None
    ) = None,
    security: str | None = None,
    slot: str | None = None,
    spell_check: bool | None = None,
    src: str | None = None,
    style: Style | None = None,
    suppress_content_editable_warning: bool | None = None,
    suppress_hydration_warning: bool | None = None,
    tab_index: int | float | None = None,
    title: str | None = None,
    translate: Literal["yes", "no"] | None = None,
    typeof: str | None = None,
    unselectable: Literal["on", "off"] | None = None,
    vocab: str | None = None,
    on_blur: FocusEventHandler | None = None,
    on_change: EventHandler | None = None,
    on_click: MouseEventHandler | None = None,
    on_context_menu: MouseEventHandler | None = None,
    on_double_click: MouseEventHandler | None = None,
    on_drag: DragEventHandler | None = None,
    on_drag_end: DragEventHandler | None = None,
    on_drag_enter: DragEventHandler | None = None,
    on_drag_leave: DragEventHandler | None = None,
    on_drag_over: DragEventHandler | None = None,
    on_drag_start: DragEventHandler | None = None,
    on_drop: DragEventHandler | None = None,
    on_focus: FocusEventHandler | None = None,
    on_input: InputEventHandler | None = None,
    on_key_down: KeyboardEventHandler | None = None,
    on_key_up: KeyboardEventHandler | None = None,
    on_mouse_down: MouseEventHandler | None = None,
    on_mouse_enter: MouseEventHandler | None = None,
    on_mouse_leave: MouseEventHandler | None = None,
    on_mouse_move: MouseEventHandler | None = None,
    on_mouse_out: MouseEventHandler | None = None,
    on_mouse_over: MouseEventHandler | None = None,
    on_mouse_up: MouseEventHandler | None = None,
    on_scroll: UIEventHandler | None = None,
    on_submit: SubmitEventHandler | None = None,
    on_wheel: WheelEventHandler | None = None,
    data: Mapping[str, DataValue] | None = None,
) -> HtmlContainerElement:
    """<audio />"""
    ...


@html_element("img")
def Img(
    *,
    about: str | None = None,
    access_key: str | None = None,
    alt: str | None = None,
    aria_activedescendant: str | None = None,
    aria_atomic: bool | None = None,
    aria_autocomplete: Literal["none", "inline", "list", "both"] | None = None,
    aria_braillelabel: str | None = None,
    aria_brailleroledescription: str | None = None,
    aria_busy: bool | None = None,
    aria_checked: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_colcount: int | float | None = None,
    aria_colindex: int | float | None = None,
    aria_colindextext: str | None = None,
    aria_colspan: int | float | None = None,
    aria_controls: str | None = None,
    aria_current: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["page"]
        | Literal["step"]
        | Literal["location"]
        | Literal["date"]
        | Literal["time"]
        | None
    ) = None,
    aria_describedby: str | None = None,
    aria_description: str | None = None,
    aria_details: str | None = None,
    aria_disabled: bool | None = None,
    aria_dropeffect: (
        Literal[
            "none",
            "copy",
            "execute",
            "link",
            "move",
            "popup",
        ]
        | None
    ) = None,
    aria_errormessage: str | None = None,
    aria_expanded: bool | None = None,
    aria_flowto: str | None = None,
    aria_grabbed: bool | None = None,
    aria_haspopup: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["menu"]
        | Literal["listbox"]
        | Literal["tree"]
        | Literal["grid"]
        | Literal["dialog"]
        | None
    ) = None,
    aria_hidden: bool | None = None,
    aria_invalid: (
        bool | Literal["false"] | Literal["true"] | Literal["grammar"] | Literal["spelling"] | None
    ) = None,
    aria_keyshortcuts: str | None = None,
    aria_label: str | None = None,
    aria_labelledby: str | None = None,
    aria_level: int | float | None = None,
    aria_live: Literal["off", "assertive", "polite"] | None = None,
    aria_modal: bool | None = None,
    aria_multiline: bool | None = None,
    aria_multiselectable: bool | None = None,
    aria_orientation: Literal["horizontal", "vertical"] | None = None,
    aria_owns: str | None = None,
    aria_placeholder: str | None = None,
    aria_posinset: int | float | None = None,
    aria_pressed: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_readonly: bool | None = None,
    aria_relevant: (
        Literal[
            "additions",
            "additions removals",
            "additions text",
            "all",
            "removals",
            "removals additions",
            "removals text",
            "text",
            "text additions",
            "text removals",
        ]
        | None
    ) = None,
    aria_required: bool | None = None,
    aria_roledescription: str | None = None,
    aria_rowcount: int | float | None = None,
    aria_rowindex: int | float | None = None,
    aria_rowindextext: str | None = None,
    aria_rowspan: int | float | None = None,
    aria_selected: bool | None = None,
    aria_setsize: int | float | None = None,
    aria_sort: Literal["none", "ascending", "descending", "other"] | None = None,
    aria_valuemax: int | float | None = None,
    aria_valuemin: int | float | None = None,
    aria_valuenow: int | float | None = None,
    aria_valuetext: str | None = None,
    auto_capitalize: (
        Literal[
            "off",
            "none",
            "on",
            "sentences",
            "words",
            "characters",
        ]
        | None
    ) = None,
    auto_correct: str | None = None,
    auto_focus: bool | None = None,
    auto_save: str | None = None,
    class_name: str | None = None,
    color: str | None = None,
    content: str | None = None,
    content_editable: bool | Literal["inherit"] | Literal["plaintext-only"] | None = None,
    context_menu: str | None = None,
    cross_origin: Literal["anonymous", "use-credentials", ""] | None = None,
    datatype: str | None = None,
    decoding: Literal["async", "auto", "sync"] | None = None,
    default_checked: bool | None = None,
    default_value: str | int | float | list[str] | None = None,
    dir: str | None = None,
    draggable: bool | None = None,
    enter_key_hint: (
        Literal[
            "enter",
            "done",
            "go",
            "next",
            "previous",
            "search",
            "send",
        ]
        | None
    ) = None,
    exportparts: str | None = None,
    fetch_priority: Literal["high", "low", "auto"] | None = None,
    height: int | float | str | None = None,
    hidden: bool | None = None,
    id: str | None = None,
    inert: bool | None = None,
    inlist: str | None = None,
    input_mode: (
        Literal[
            "none",
            "text",
            "tel",
            "url",
            "email",
            "numeric",
            "decimal",
            "search",
        ]
        | None
    ) = None,
    is_: str | None = None,
    item_id: str | None = None,
    item_prop: str | None = None,
    item_ref: str | None = None,
    item_scope: bool | None = None,
    item_type: str | None = None,
    lang: str | None = None,
    loading: Literal["eager", "lazy"] | None = None,
    nonce: str | None = None,
    part: str | None = None,
    popover: Literal["", "auto", "manual", "hint"] | None = None,
    popover_target: str | None = None,
    popover_target_action: Literal["toggle", "show", "hide"] | None = None,
    prefix: str | None = None,
    property: str | None = None,
    radio_group: str | None = None,
    referrer_policy: (
        Literal[
            "",
            "no-referrer",
            "no-referrer-when-downgrade",
            "origin",
            "origin-when-cross-origin",
            "same-origin",
            "strict-origin",
            "strict-origin-when-cross-origin",
            "unsafe-url",
        ]
        | None
    ) = None,
    rel: str | None = None,
    resource: str | None = None,
    results: int | float | None = None,
    rev: str | None = None,
    role: (
        Literal[
            "alert",
            "alertdialog",
            "application",
            "article",
            "banner",
            "button",
            "cell",
            "checkbox",
            "columnheader",
            "combobox",
            "complementary",
            "contentinfo",
            "definition",
            "dialog",
            "directory",
            "document",
            "feed",
            "figure",
            "form",
            "grid",
            "gridcell",
            "group",
            "heading",
            "img",
            "link",
            "list",
            "listbox",
            "listitem",
            "log",
            "main",
            "marquee",
            "math",
            "menu",
            "menubar",
            "menuitem",
            "menuitemcheckbox",
            "menuitemradio",
            "navigation",
            "none",
            "note",
            "option",
            "presentation",
            "progressbar",
            "radio",
            "radiogroup",
            "region",
            "row",
            "rowgroup",
            "rowheader",
            "scrollbar",
            "search",
            "searchbox",
            "separator",
            "slider",
            "spinbutton",
            "status",
            "switch",
            "tab",
            "table",
            "tablist",
            "tabpanel",
            "term",
            "textbox",
            "timer",
            "toolbar",
            "tooltip",
            "tree",
            "treegrid",
            "treeitem",
        ]
        | None
    ) = None,
    security: str | None = None,
    sizes: str | None = None,
    slot: str | None = None,
    spell_check: bool | None = None,
    src: str | None = None,
    src_set: str | None = None,
    style: Style | None = None,
    suppress_content_editable_warning: bool | None = None,
    suppress_hydration_warning: bool | None = None,
    tab_index: int | float | None = None,
    title: str | None = None,
    translate: Literal["yes", "no"] | None = None,
    typeof: str | None = None,
    unselectable: Literal["on", "off"] | None = None,
    use_map: str | None = None,
    vocab: str | None = None,
    width: int | float | str | None = None,
    on_blur: FocusEventHandler | None = None,
    on_change: EventHandler | None = None,
    on_click: MouseEventHandler | None = None,
    on_context_menu: MouseEventHandler | None = None,
    on_double_click: MouseEventHandler | None = None,
    on_drag: DragEventHandler | None = None,
    on_drag_end: DragEventHandler | None = None,
    on_drag_enter: DragEventHandler | None = None,
    on_drag_leave: DragEventHandler | None = None,
    on_drag_over: DragEventHandler | None = None,
    on_drag_start: DragEventHandler | None = None,
    on_drop: DragEventHandler | None = None,
    on_focus: FocusEventHandler | None = None,
    on_input: InputEventHandler | None = None,
    on_key_down: KeyboardEventHandler | None = None,
    on_key_up: KeyboardEventHandler | None = None,
    on_mouse_down: MouseEventHandler | None = None,
    on_mouse_enter: MouseEventHandler | None = None,
    on_mouse_leave: MouseEventHandler | None = None,
    on_mouse_move: MouseEventHandler | None = None,
    on_mouse_out: MouseEventHandler | None = None,
    on_mouse_over: MouseEventHandler | None = None,
    on_mouse_up: MouseEventHandler | None = None,
    on_scroll: UIEventHandler | None = None,
    on_submit: SubmitEventHandler | None = None,
    on_wheel: WheelEventHandler | None = None,
    data: Mapping[str, DataValue] | None = None,
) -> Element:
    """<img />"""
    ...


@html_element("map", is_container=True)
def Map(
    *,
    about: str | None = None,
    access_key: str | None = None,
    aria_activedescendant: str | None = None,
    aria_atomic: bool | None = None,
    aria_autocomplete: Literal["none", "inline", "list", "both"] | None = None,
    aria_braillelabel: str | None = None,
    aria_brailleroledescription: str | None = None,
    aria_busy: bool | None = None,
    aria_checked: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_colcount: int | float | None = None,
    aria_colindex: int | float | None = None,
    aria_colindextext: str | None = None,
    aria_colspan: int | float | None = None,
    aria_controls: str | None = None,
    aria_current: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["page"]
        | Literal["step"]
        | Literal["location"]
        | Literal["date"]
        | Literal["time"]
        | None
    ) = None,
    aria_describedby: str | None = None,
    aria_description: str | None = None,
    aria_details: str | None = None,
    aria_disabled: bool | None = None,
    aria_dropeffect: (
        Literal[
            "none",
            "copy",
            "execute",
            "link",
            "move",
            "popup",
        ]
        | None
    ) = None,
    aria_errormessage: str | None = None,
    aria_expanded: bool | None = None,
    aria_flowto: str | None = None,
    aria_grabbed: bool | None = None,
    aria_haspopup: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["menu"]
        | Literal["listbox"]
        | Literal["tree"]
        | Literal["grid"]
        | Literal["dialog"]
        | None
    ) = None,
    aria_hidden: bool | None = None,
    aria_invalid: (
        bool | Literal["false"] | Literal["true"] | Literal["grammar"] | Literal["spelling"] | None
    ) = None,
    aria_keyshortcuts: str | None = None,
    aria_label: str | None = None,
    aria_labelledby: str | None = None,
    aria_level: int | float | None = None,
    aria_live: Literal["off", "assertive", "polite"] | None = None,
    aria_modal: bool | None = None,
    aria_multiline: bool | None = None,
    aria_multiselectable: bool | None = None,
    aria_orientation: Literal["horizontal", "vertical"] | None = None,
    aria_owns: str | None = None,
    aria_placeholder: str | None = None,
    aria_posinset: int | float | None = None,
    aria_pressed: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_readonly: bool | None = None,
    aria_relevant: (
        Literal[
            "additions",
            "additions removals",
            "additions text",
            "all",
            "removals",
            "removals additions",
            "removals text",
            "text",
            "text additions",
            "text removals",
        ]
        | None
    ) = None,
    aria_required: bool | None = None,
    aria_roledescription: str | None = None,
    aria_rowcount: int | float | None = None,
    aria_rowindex: int | float | None = None,
    aria_rowindextext: str | None = None,
    aria_rowspan: int | float | None = None,
    aria_selected: bool | None = None,
    aria_setsize: int | float | None = None,
    aria_sort: Literal["none", "ascending", "descending", "other"] | None = None,
    aria_valuemax: int | float | None = None,
    aria_valuemin: int | float | None = None,
    aria_valuenow: int | float | None = None,
    aria_valuetext: str | None = None,
    auto_capitalize: (
        Literal[
            "off",
            "none",
            "on",
            "sentences",
            "words",
            "characters",
        ]
        | None
    ) = None,
    auto_correct: str | None = None,
    auto_focus: bool | None = None,
    auto_save: str | None = None,
    class_name: str | None = None,
    color: str | None = None,
    content: str | None = None,
    content_editable: bool | Literal["inherit"] | Literal["plaintext-only"] | None = None,
    context_menu: str | None = None,
    datatype: str | None = None,
    default_checked: bool | None = None,
    default_value: str | int | float | list[str] | None = None,
    dir: str | None = None,
    draggable: bool | None = None,
    enter_key_hint: (
        Literal[
            "enter",
            "done",
            "go",
            "next",
            "previous",
            "search",
            "send",
        ]
        | None
    ) = None,
    exportparts: str | None = None,
    hidden: bool | None = None,
    id: str | None = None,
    inert: bool | None = None,
    inlist: str | None = None,
    input_mode: (
        Literal[
            "none",
            "text",
            "tel",
            "url",
            "email",
            "numeric",
            "decimal",
            "search",
        ]
        | None
    ) = None,
    is_: str | None = None,
    item_id: str | None = None,
    item_prop: str | None = None,
    item_ref: str | None = None,
    item_scope: bool | None = None,
    item_type: str | None = None,
    lang: str | None = None,
    name: str | None = None,
    nonce: str | None = None,
    part: str | None = None,
    popover: Literal["", "auto", "manual", "hint"] | None = None,
    popover_target: str | None = None,
    popover_target_action: Literal["toggle", "show", "hide"] | None = None,
    prefix: str | None = None,
    property: str | None = None,
    radio_group: str | None = None,
    rel: str | None = None,
    resource: str | None = None,
    results: int | float | None = None,
    rev: str | None = None,
    role: (
        Literal[
            "alert",
            "alertdialog",
            "application",
            "article",
            "banner",
            "button",
            "cell",
            "checkbox",
            "columnheader",
            "combobox",
            "complementary",
            "contentinfo",
            "definition",
            "dialog",
            "directory",
            "document",
            "feed",
            "figure",
            "form",
            "grid",
            "gridcell",
            "group",
            "heading",
            "img",
            "link",
            "list",
            "listbox",
            "listitem",
            "log",
            "main",
            "marquee",
            "math",
            "menu",
            "menubar",
            "menuitem",
            "menuitemcheckbox",
            "menuitemradio",
            "navigation",
            "none",
            "note",
            "option",
            "presentation",
            "progressbar",
            "radio",
            "radiogroup",
            "region",
            "row",
            "rowgroup",
            "rowheader",
            "scrollbar",
            "search",
            "searchbox",
            "separator",
            "slider",
            "spinbutton",
            "status",
            "switch",
            "tab",
            "table",
            "tablist",
            "tabpanel",
            "term",
            "textbox",
            "timer",
            "toolbar",
            "tooltip",
            "tree",
            "treegrid",
            "treeitem",
        ]
        | None
    ) = None,
    security: str | None = None,
    slot: str | None = None,
    spell_check: bool | None = None,
    style: Style | None = None,
    suppress_content_editable_warning: bool | None = None,
    suppress_hydration_warning: bool | None = None,
    tab_index: int | float | None = None,
    title: str | None = None,
    translate: Literal["yes", "no"] | None = None,
    typeof: str | None = None,
    unselectable: Literal["on", "off"] | None = None,
    vocab: str | None = None,
    on_blur: FocusEventHandler | None = None,
    on_change: EventHandler | None = None,
    on_click: MouseEventHandler | None = None,
    on_context_menu: MouseEventHandler | None = None,
    on_double_click: MouseEventHandler | None = None,
    on_drag: DragEventHandler | None = None,
    on_drag_end: DragEventHandler | None = None,
    on_drag_enter: DragEventHandler | None = None,
    on_drag_leave: DragEventHandler | None = None,
    on_drag_over: DragEventHandler | None = None,
    on_drag_start: DragEventHandler | None = None,
    on_drop: DragEventHandler | None = None,
    on_focus: FocusEventHandler | None = None,
    on_input: InputEventHandler | None = None,
    on_key_down: KeyboardEventHandler | None = None,
    on_key_up: KeyboardEventHandler | None = None,
    on_mouse_down: MouseEventHandler | None = None,
    on_mouse_enter: MouseEventHandler | None = None,
    on_mouse_leave: MouseEventHandler | None = None,
    on_mouse_move: MouseEventHandler | None = None,
    on_mouse_out: MouseEventHandler | None = None,
    on_mouse_over: MouseEventHandler | None = None,
    on_mouse_up: MouseEventHandler | None = None,
    on_scroll: UIEventHandler | None = None,
    on_submit: SubmitEventHandler | None = None,
    on_wheel: WheelEventHandler | None = None,
    data: Mapping[str, DataValue] | None = None,
) -> HtmlContainerElement:
    """<map />"""
    ...


@html_element("picture", is_container=True)
def Picture(
    *,
    about: str | None = None,
    access_key: str | None = None,
    aria_activedescendant: str | None = None,
    aria_atomic: bool | None = None,
    aria_autocomplete: Literal["none", "inline", "list", "both"] | None = None,
    aria_braillelabel: str | None = None,
    aria_brailleroledescription: str | None = None,
    aria_busy: bool | None = None,
    aria_checked: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_colcount: int | float | None = None,
    aria_colindex: int | float | None = None,
    aria_colindextext: str | None = None,
    aria_colspan: int | float | None = None,
    aria_controls: str | None = None,
    aria_current: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["page"]
        | Literal["step"]
        | Literal["location"]
        | Literal["date"]
        | Literal["time"]
        | None
    ) = None,
    aria_describedby: str | None = None,
    aria_description: str | None = None,
    aria_details: str | None = None,
    aria_disabled: bool | None = None,
    aria_dropeffect: (
        Literal[
            "none",
            "copy",
            "execute",
            "link",
            "move",
            "popup",
        ]
        | None
    ) = None,
    aria_errormessage: str | None = None,
    aria_expanded: bool | None = None,
    aria_flowto: str | None = None,
    aria_grabbed: bool | None = None,
    aria_haspopup: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["menu"]
        | Literal["listbox"]
        | Literal["tree"]
        | Literal["grid"]
        | Literal["dialog"]
        | None
    ) = None,
    aria_hidden: bool | None = None,
    aria_invalid: (
        bool | Literal["false"] | Literal["true"] | Literal["grammar"] | Literal["spelling"] | None
    ) = None,
    aria_keyshortcuts: str | None = None,
    aria_label: str | None = None,
    aria_labelledby: str | None = None,
    aria_level: int | float | None = None,
    aria_live: Literal["off", "assertive", "polite"] | None = None,
    aria_modal: bool | None = None,
    aria_multiline: bool | None = None,
    aria_multiselectable: bool | None = None,
    aria_orientation: Literal["horizontal", "vertical"] | None = None,
    aria_owns: str | None = None,
    aria_placeholder: str | None = None,
    aria_posinset: int | float | None = None,
    aria_pressed: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_readonly: bool | None = None,
    aria_relevant: (
        Literal[
            "additions",
            "additions removals",
            "additions text",
            "all",
            "removals",
            "removals additions",
            "removals text",
            "text",
            "text additions",
            "text removals",
        ]
        | None
    ) = None,
    aria_required: bool | None = None,
    aria_roledescription: str | None = None,
    aria_rowcount: int | float | None = None,
    aria_rowindex: int | float | None = None,
    aria_rowindextext: str | None = None,
    aria_rowspan: int | float | None = None,
    aria_selected: bool | None = None,
    aria_setsize: int | float | None = None,
    aria_sort: Literal["none", "ascending", "descending", "other"] | None = None,
    aria_valuemax: int | float | None = None,
    aria_valuemin: int | float | None = None,
    aria_valuenow: int | float | None = None,
    aria_valuetext: str | None = None,
    auto_capitalize: (
        Literal[
            "off",
            "none",
            "on",
            "sentences",
            "words",
            "characters",
        ]
        | None
    ) = None,
    auto_correct: str | None = None,
    auto_focus: bool | None = None,
    auto_save: str | None = None,
    class_name: str | None = None,
    color: str | None = None,
    content: str | None = None,
    content_editable: bool | Literal["inherit"] | Literal["plaintext-only"] | None = None,
    context_menu: str | None = None,
    datatype: str | None = None,
    default_checked: bool | None = None,
    default_value: str | int | float | list[str] | None = None,
    dir: str | None = None,
    draggable: bool | None = None,
    enter_key_hint: (
        Literal[
            "enter",
            "done",
            "go",
            "next",
            "previous",
            "search",
            "send",
        ]
        | None
    ) = None,
    exportparts: str | None = None,
    hidden: bool | None = None,
    id: str | None = None,
    inert: bool | None = None,
    inlist: str | None = None,
    input_mode: (
        Literal[
            "none",
            "text",
            "tel",
            "url",
            "email",
            "numeric",
            "decimal",
            "search",
        ]
        | None
    ) = None,
    is_: str | None = None,
    item_id: str | None = None,
    item_prop: str | None = None,
    item_ref: str | None = None,
    item_scope: bool | None = None,
    item_type: str | None = None,
    lang: str | None = None,
    nonce: str | None = None,
    part: str | None = None,
    popover: Literal["", "auto", "manual", "hint"] | None = None,
    popover_target: str | None = None,
    popover_target_action: Literal["toggle", "show", "hide"] | None = None,
    prefix: str | None = None,
    property: str | None = None,
    radio_group: str | None = None,
    rel: str | None = None,
    resource: str | None = None,
    results: int | float | None = None,
    rev: str | None = None,
    role: (
        Literal[
            "alert",
            "alertdialog",
            "application",
            "article",
            "banner",
            "button",
            "cell",
            "checkbox",
            "columnheader",
            "combobox",
            "complementary",
            "contentinfo",
            "definition",
            "dialog",
            "directory",
            "document",
            "feed",
            "figure",
            "form",
            "grid",
            "gridcell",
            "group",
            "heading",
            "img",
            "link",
            "list",
            "listbox",
            "listitem",
            "log",
            "main",
            "marquee",
            "math",
            "menu",
            "menubar",
            "menuitem",
            "menuitemcheckbox",
            "menuitemradio",
            "navigation",
            "none",
            "note",
            "option",
            "presentation",
            "progressbar",
            "radio",
            "radiogroup",
            "region",
            "row",
            "rowgroup",
            "rowheader",
            "scrollbar",
            "search",
            "searchbox",
            "separator",
            "slider",
            "spinbutton",
            "status",
            "switch",
            "tab",
            "table",
            "tablist",
            "tabpanel",
            "term",
            "textbox",
            "timer",
            "toolbar",
            "tooltip",
            "tree",
            "treegrid",
            "treeitem",
        ]
        | None
    ) = None,
    security: str | None = None,
    slot: str | None = None,
    spell_check: bool | None = None,
    style: Style | None = None,
    suppress_content_editable_warning: bool | None = None,
    suppress_hydration_warning: bool | None = None,
    tab_index: int | float | None = None,
    title: str | None = None,
    translate: Literal["yes", "no"] | None = None,
    typeof: str | None = None,
    unselectable: Literal["on", "off"] | None = None,
    vocab: str | None = None,
    on_blur: FocusEventHandler | None = None,
    on_change: EventHandler | None = None,
    on_click: MouseEventHandler | None = None,
    on_context_menu: MouseEventHandler | None = None,
    on_double_click: MouseEventHandler | None = None,
    on_drag: DragEventHandler | None = None,
    on_drag_end: DragEventHandler | None = None,
    on_drag_enter: DragEventHandler | None = None,
    on_drag_leave: DragEventHandler | None = None,
    on_drag_over: DragEventHandler | None = None,
    on_drag_start: DragEventHandler | None = None,
    on_drop: DragEventHandler | None = None,
    on_focus: FocusEventHandler | None = None,
    on_input: InputEventHandler | None = None,
    on_key_down: KeyboardEventHandler | None = None,
    on_key_up: KeyboardEventHandler | None = None,
    on_mouse_down: MouseEventHandler | None = None,
    on_mouse_enter: MouseEventHandler | None = None,
    on_mouse_leave: MouseEventHandler | None = None,
    on_mouse_move: MouseEventHandler | None = None,
    on_mouse_out: MouseEventHandler | None = None,
    on_mouse_over: MouseEventHandler | None = None,
    on_mouse_up: MouseEventHandler | None = None,
    on_scroll: UIEventHandler | None = None,
    on_submit: SubmitEventHandler | None = None,
    on_wheel: WheelEventHandler | None = None,
    data: Mapping[str, DataValue] | None = None,
) -> HtmlContainerElement:
    """<picture />"""
    ...


@html_element("source")
def Source(
    *,
    about: str | None = None,
    access_key: str | None = None,
    aria_activedescendant: str | None = None,
    aria_atomic: bool | None = None,
    aria_autocomplete: Literal["none", "inline", "list", "both"] | None = None,
    aria_braillelabel: str | None = None,
    aria_brailleroledescription: str | None = None,
    aria_busy: bool | None = None,
    aria_checked: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_colcount: int | float | None = None,
    aria_colindex: int | float | None = None,
    aria_colindextext: str | None = None,
    aria_colspan: int | float | None = None,
    aria_controls: str | None = None,
    aria_current: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["page"]
        | Literal["step"]
        | Literal["location"]
        | Literal["date"]
        | Literal["time"]
        | None
    ) = None,
    aria_describedby: str | None = None,
    aria_description: str | None = None,
    aria_details: str | None = None,
    aria_disabled: bool | None = None,
    aria_dropeffect: (
        Literal[
            "none",
            "copy",
            "execute",
            "link",
            "move",
            "popup",
        ]
        | None
    ) = None,
    aria_errormessage: str | None = None,
    aria_expanded: bool | None = None,
    aria_flowto: str | None = None,
    aria_grabbed: bool | None = None,
    aria_haspopup: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["menu"]
        | Literal["listbox"]
        | Literal["tree"]
        | Literal["grid"]
        | Literal["dialog"]
        | None
    ) = None,
    aria_hidden: bool | None = None,
    aria_invalid: (
        bool | Literal["false"] | Literal["true"] | Literal["grammar"] | Literal["spelling"] | None
    ) = None,
    aria_keyshortcuts: str | None = None,
    aria_label: str | None = None,
    aria_labelledby: str | None = None,
    aria_level: int | float | None = None,
    aria_live: Literal["off", "assertive", "polite"] | None = None,
    aria_modal: bool | None = None,
    aria_multiline: bool | None = None,
    aria_multiselectable: bool | None = None,
    aria_orientation: Literal["horizontal", "vertical"] | None = None,
    aria_owns: str | None = None,
    aria_placeholder: str | None = None,
    aria_posinset: int | float | None = None,
    aria_pressed: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_readonly: bool | None = None,
    aria_relevant: (
        Literal[
            "additions",
            "additions removals",
            "additions text",
            "all",
            "removals",
            "removals additions",
            "removals text",
            "text",
            "text additions",
            "text removals",
        ]
        | None
    ) = None,
    aria_required: bool | None = None,
    aria_roledescription: str | None = None,
    aria_rowcount: int | float | None = None,
    aria_rowindex: int | float | None = None,
    aria_rowindextext: str | None = None,
    aria_rowspan: int | float | None = None,
    aria_selected: bool | None = None,
    aria_setsize: int | float | None = None,
    aria_sort: Literal["none", "ascending", "descending", "other"] | None = None,
    aria_valuemax: int | float | None = None,
    aria_valuemin: int | float | None = None,
    aria_valuenow: int | float | None = None,
    aria_valuetext: str | None = None,
    auto_capitalize: (
        Literal[
            "off",
            "none",
            "on",
            "sentences",
            "words",
            "characters",
        ]
        | None
    ) = None,
    auto_correct: str | None = None,
    auto_focus: bool | None = None,
    auto_save: str | None = None,
    class_name: str | None = None,
    color: str | None = None,
    content: str | None = None,
    content_editable: bool | Literal["inherit"] | Literal["plaintext-only"] | None = None,
    context_menu: str | None = None,
    datatype: str | None = None,
    default_checked: bool | None = None,
    default_value: str | int | float | list[str] | None = None,
    dir: str | None = None,
    draggable: bool | None = None,
    enter_key_hint: (
        Literal[
            "enter",
            "done",
            "go",
            "next",
            "previous",
            "search",
            "send",
        ]
        | None
    ) = None,
    exportparts: str | None = None,
    height: int | float | str | None = None,
    hidden: bool | None = None,
    id: str | None = None,
    inert: bool | None = None,
    inlist: str | None = None,
    input_mode: (
        Literal[
            "none",
            "text",
            "tel",
            "url",
            "email",
            "numeric",
            "decimal",
            "search",
        ]
        | None
    ) = None,
    is_: str | None = None,
    item_id: str | None = None,
    item_prop: str | None = None,
    item_ref: str | None = None,
    item_scope: bool | None = None,
    item_type: str | None = None,
    lang: str | None = None,
    media: str | None = None,
    nonce: str | None = None,
    part: str | None = None,
    popover: Literal["", "auto", "manual", "hint"] | None = None,
    popover_target: str | None = None,
    popover_target_action: Literal["toggle", "show", "hide"] | None = None,
    prefix: str | None = None,
    property: str | None = None,
    radio_group: str | None = None,
    rel: str | None = None,
    resource: str | None = None,
    results: int | float | None = None,
    rev: str | None = None,
    role: (
        Literal[
            "alert",
            "alertdialog",
            "application",
            "article",
            "banner",
            "button",
            "cell",
            "checkbox",
            "columnheader",
            "combobox",
            "complementary",
            "contentinfo",
            "definition",
            "dialog",
            "directory",
            "document",
            "feed",
            "figure",
            "form",
            "grid",
            "gridcell",
            "group",
            "heading",
            "img",
            "link",
            "list",
            "listbox",
            "listitem",
            "log",
            "main",
            "marquee",
            "math",
            "menu",
            "menubar",
            "menuitem",
            "menuitemcheckbox",
            "menuitemradio",
            "navigation",
            "none",
            "note",
            "option",
            "presentation",
            "progressbar",
            "radio",
            "radiogroup",
            "region",
            "row",
            "rowgroup",
            "rowheader",
            "scrollbar",
            "search",
            "searchbox",
            "separator",
            "slider",
            "spinbutton",
            "status",
            "switch",
            "tab",
            "table",
            "tablist",
            "tabpanel",
            "term",
            "textbox",
            "timer",
            "toolbar",
            "tooltip",
            "tree",
            "treegrid",
            "treeitem",
        ]
        | None
    ) = None,
    security: str | None = None,
    sizes: str | None = None,
    slot: str | None = None,
    spell_check: bool | None = None,
    src: str | None = None,
    src_set: str | None = None,
    style: Style | None = None,
    suppress_content_editable_warning: bool | None = None,
    suppress_hydration_warning: bool | None = None,
    tab_index: int | float | None = None,
    title: str | None = None,
    translate: Literal["yes", "no"] | None = None,
    type: str | None = None,
    typeof: str | None = None,
    unselectable: Literal["on", "off"] | None = None,
    vocab: str | None = None,
    width: int | float | str | None = None,
    on_blur: FocusEventHandler | None = None,
    on_change: EventHandler | None = None,
    on_click: MouseEventHandler | None = None,
    on_context_menu: MouseEventHandler | None = None,
    on_double_click: MouseEventHandler | None = None,
    on_drag: DragEventHandler | None = None,
    on_drag_end: DragEventHandler | None = None,
    on_drag_enter: DragEventHandler | None = None,
    on_drag_leave: DragEventHandler | None = None,
    on_drag_over: DragEventHandler | None = None,
    on_drag_start: DragEventHandler | None = None,
    on_drop: DragEventHandler | None = None,
    on_focus: FocusEventHandler | None = None,
    on_input: InputEventHandler | None = None,
    on_key_down: KeyboardEventHandler | None = None,
    on_key_up: KeyboardEventHandler | None = None,
    on_mouse_down: MouseEventHandler | None = None,
    on_mouse_enter: MouseEventHandler | None = None,
    on_mouse_leave: MouseEventHandler | None = None,
    on_mouse_move: MouseEventHandler | None = None,
    on_mouse_out: MouseEventHandler | None = None,
    on_mouse_over: MouseEventHandler | None = None,
    on_mouse_up: MouseEventHandler | None = None,
    on_scroll: UIEventHandler | None = None,
    on_submit: SubmitEventHandler | None = None,
    on_wheel: WheelEventHandler | None = None,
    data: Mapping[str, DataValue] | None = None,
) -> Element:
    """<source />"""
    ...


@html_element("track")
def Track(
    *,
    about: str | None = None,
    access_key: str | None = None,
    aria_activedescendant: str | None = None,
    aria_atomic: bool | None = None,
    aria_autocomplete: Literal["none", "inline", "list", "both"] | None = None,
    aria_braillelabel: str | None = None,
    aria_brailleroledescription: str | None = None,
    aria_busy: bool | None = None,
    aria_checked: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_colcount: int | float | None = None,
    aria_colindex: int | float | None = None,
    aria_colindextext: str | None = None,
    aria_colspan: int | float | None = None,
    aria_controls: str | None = None,
    aria_current: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["page"]
        | Literal["step"]
        | Literal["location"]
        | Literal["date"]
        | Literal["time"]
        | None
    ) = None,
    aria_describedby: str | None = None,
    aria_description: str | None = None,
    aria_details: str | None = None,
    aria_disabled: bool | None = None,
    aria_dropeffect: (
        Literal[
            "none",
            "copy",
            "execute",
            "link",
            "move",
            "popup",
        ]
        | None
    ) = None,
    aria_errormessage: str | None = None,
    aria_expanded: bool | None = None,
    aria_flowto: str | None = None,
    aria_grabbed: bool | None = None,
    aria_haspopup: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["menu"]
        | Literal["listbox"]
        | Literal["tree"]
        | Literal["grid"]
        | Literal["dialog"]
        | None
    ) = None,
    aria_hidden: bool | None = None,
    aria_invalid: (
        bool | Literal["false"] | Literal["true"] | Literal["grammar"] | Literal["spelling"] | None
    ) = None,
    aria_keyshortcuts: str | None = None,
    aria_label: str | None = None,
    aria_labelledby: str | None = None,
    aria_level: int | float | None = None,
    aria_live: Literal["off", "assertive", "polite"] | None = None,
    aria_modal: bool | None = None,
    aria_multiline: bool | None = None,
    aria_multiselectable: bool | None = None,
    aria_orientation: Literal["horizontal", "vertical"] | None = None,
    aria_owns: str | None = None,
    aria_placeholder: str | None = None,
    aria_posinset: int | float | None = None,
    aria_pressed: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_readonly: bool | None = None,
    aria_relevant: (
        Literal[
            "additions",
            "additions removals",
            "additions text",
            "all",
            "removals",
            "removals additions",
            "removals text",
            "text",
            "text additions",
            "text removals",
        ]
        | None
    ) = None,
    aria_required: bool | None = None,
    aria_roledescription: str | None = None,
    aria_rowcount: int | float | None = None,
    aria_rowindex: int | float | None = None,
    aria_rowindextext: str | None = None,
    aria_rowspan: int | float | None = None,
    aria_selected: bool | None = None,
    aria_setsize: int | float | None = None,
    aria_sort: Literal["none", "ascending", "descending", "other"] | None = None,
    aria_valuemax: int | float | None = None,
    aria_valuemin: int | float | None = None,
    aria_valuenow: int | float | None = None,
    aria_valuetext: str | None = None,
    auto_capitalize: (
        Literal[
            "off",
            "none",
            "on",
            "sentences",
            "words",
            "characters",
        ]
        | None
    ) = None,
    auto_correct: str | None = None,
    auto_focus: bool | None = None,
    auto_save: str | None = None,
    class_name: str | None = None,
    color: str | None = None,
    content: str | None = None,
    content_editable: bool | Literal["inherit"] | Literal["plaintext-only"] | None = None,
    context_menu: str | None = None,
    datatype: str | None = None,
    default: bool | None = None,
    default_checked: bool | None = None,
    default_value: str | int | float | list[str] | None = None,
    dir: str | None = None,
    draggable: bool | None = None,
    enter_key_hint: (
        Literal[
            "enter",
            "done",
            "go",
            "next",
            "previous",
            "search",
            "send",
        ]
        | None
    ) = None,
    exportparts: str | None = None,
    hidden: bool | None = None,
    id: str | None = None,
    inert: bool | None = None,
    inlist: str | None = None,
    input_mode: (
        Literal[
            "none",
            "text",
            "tel",
            "url",
            "email",
            "numeric",
            "decimal",
            "search",
        ]
        | None
    ) = None,
    is_: str | None = None,
    item_id: str | None = None,
    item_prop: str | None = None,
    item_ref: str | None = None,
    item_scope: bool | None = None,
    item_type: str | None = None,
    kind: str | None = None,
    label: str | None = None,
    lang: str | None = None,
    nonce: str | None = None,
    part: str | None = None,
    popover: Literal["", "auto", "manual", "hint"] | None = None,
    popover_target: str | None = None,
    popover_target_action: Literal["toggle", "show", "hide"] | None = None,
    prefix: str | None = None,
    property: str | None = None,
    radio_group: str | None = None,
    rel: str | None = None,
    resource: str | None = None,
    results: int | float | None = None,
    rev: str | None = None,
    role: (
        Literal[
            "alert",
            "alertdialog",
            "application",
            "article",
            "banner",
            "button",
            "cell",
            "checkbox",
            "columnheader",
            "combobox",
            "complementary",
            "contentinfo",
            "definition",
            "dialog",
            "directory",
            "document",
            "feed",
            "figure",
            "form",
            "grid",
            "gridcell",
            "group",
            "heading",
            "img",
            "link",
            "list",
            "listbox",
            "listitem",
            "log",
            "main",
            "marquee",
            "math",
            "menu",
            "menubar",
            "menuitem",
            "menuitemcheckbox",
            "menuitemradio",
            "navigation",
            "none",
            "note",
            "option",
            "presentation",
            "progressbar",
            "radio",
            "radiogroup",
            "region",
            "row",
            "rowgroup",
            "rowheader",
            "scrollbar",
            "search",
            "searchbox",
            "separator",
            "slider",
            "spinbutton",
            "status",
            "switch",
            "tab",
            "table",
            "tablist",
            "tabpanel",
            "term",
            "textbox",
            "timer",
            "toolbar",
            "tooltip",
            "tree",
            "treegrid",
            "treeitem",
        ]
        | None
    ) = None,
    security: str | None = None,
    slot: str | None = None,
    spell_check: bool | None = None,
    src: str | None = None,
    src_lang: str | None = None,
    style: Style | None = None,
    suppress_content_editable_warning: bool | None = None,
    suppress_hydration_warning: bool | None = None,
    tab_index: int | float | None = None,
    title: str | None = None,
    translate: Literal["yes", "no"] | None = None,
    typeof: str | None = None,
    unselectable: Literal["on", "off"] | None = None,
    vocab: str | None = None,
    on_blur: FocusEventHandler | None = None,
    on_change: EventHandler | None = None,
    on_click: MouseEventHandler | None = None,
    on_context_menu: MouseEventHandler | None = None,
    on_double_click: MouseEventHandler | None = None,
    on_drag: DragEventHandler | None = None,
    on_drag_end: DragEventHandler | None = None,
    on_drag_enter: DragEventHandler | None = None,
    on_drag_leave: DragEventHandler | None = None,
    on_drag_over: DragEventHandler | None = None,
    on_drag_start: DragEventHandler | None = None,
    on_drop: DragEventHandler | None = None,
    on_focus: FocusEventHandler | None = None,
    on_input: InputEventHandler | None = None,
    on_key_down: KeyboardEventHandler | None = None,
    on_key_up: KeyboardEventHandler | None = None,
    on_mouse_down: MouseEventHandler | None = None,
    on_mouse_enter: MouseEventHandler | None = None,
    on_mouse_leave: MouseEventHandler | None = None,
    on_mouse_move: MouseEventHandler | None = None,
    on_mouse_out: MouseEventHandler | None = None,
    on_mouse_over: MouseEventHandler | None = None,
    on_mouse_up: MouseEventHandler | None = None,
    on_scroll: UIEventHandler | None = None,
    on_submit: SubmitEventHandler | None = None,
    on_wheel: WheelEventHandler | None = None,
    data: Mapping[str, DataValue] | None = None,
) -> Element:
    """<track />"""
    ...


@html_element("video", is_container=True)
def Video(
    *,
    about: str | None = None,
    access_key: str | None = None,
    aria_activedescendant: str | None = None,
    aria_atomic: bool | None = None,
    aria_autocomplete: Literal["none", "inline", "list", "both"] | None = None,
    aria_braillelabel: str | None = None,
    aria_brailleroledescription: str | None = None,
    aria_busy: bool | None = None,
    aria_checked: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_colcount: int | float | None = None,
    aria_colindex: int | float | None = None,
    aria_colindextext: str | None = None,
    aria_colspan: int | float | None = None,
    aria_controls: str | None = None,
    aria_current: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["page"]
        | Literal["step"]
        | Literal["location"]
        | Literal["date"]
        | Literal["time"]
        | None
    ) = None,
    aria_describedby: str | None = None,
    aria_description: str | None = None,
    aria_details: str | None = None,
    aria_disabled: bool | None = None,
    aria_dropeffect: (
        Literal[
            "none",
            "copy",
            "execute",
            "link",
            "move",
            "popup",
        ]
        | None
    ) = None,
    aria_errormessage: str | None = None,
    aria_expanded: bool | None = None,
    aria_flowto: str | None = None,
    aria_grabbed: bool | None = None,
    aria_haspopup: (
        bool
        | Literal["false"]
        | Literal["true"]
        | Literal["menu"]
        | Literal["listbox"]
        | Literal["tree"]
        | Literal["grid"]
        | Literal["dialog"]
        | None
    ) = None,
    aria_hidden: bool | None = None,
    aria_invalid: (
        bool | Literal["false"] | Literal["true"] | Literal["grammar"] | Literal["spelling"] | None
    ) = None,
    aria_keyshortcuts: str | None = None,
    aria_label: str | None = None,
    aria_labelledby: str | None = None,
    aria_level: int | float | None = None,
    aria_live: Literal["off", "assertive", "polite"] | None = None,
    aria_modal: bool | None = None,
    aria_multiline: bool | None = None,
    aria_multiselectable: bool | None = None,
    aria_orientation: Literal["horizontal", "vertical"] | None = None,
    aria_owns: str | None = None,
    aria_placeholder: str | None = None,
    aria_posinset: int | float | None = None,
    aria_pressed: bool | Literal["false"] | Literal["mixed"] | Literal["true"] | None = None,
    aria_readonly: bool | None = None,
    aria_relevant: (
        Literal[
            "additions",
            "additions removals",
            "additions text",
            "all",
            "removals",
            "removals additions",
            "removals text",
            "text",
            "text additions",
            "text removals",
        ]
        | None
    ) = None,
    aria_required: bool | None = None,
    aria_roledescription: str | None = None,
    aria_rowcount: int | float | None = None,
    aria_rowindex: int | float | None = None,
    aria_rowindextext: str | None = None,
    aria_rowspan: int | float | None = None,
    aria_selected: bool | None = None,
    aria_setsize: int | float | None = None,
    aria_sort: Literal["none", "ascending", "descending", "other"] | None = None,
    aria_valuemax: int | float | None = None,
    aria_valuemin: int | float | None = None,
    aria_valuenow: int | float | None = None,
    aria_valuetext: str | None = None,
    auto_capitalize: (
        Literal[
            "off",
            "none",
            "on",
            "sentences",
            "words",
            "characters",
        ]
        | None
    ) = None,
    auto_correct: str | None = None,
    auto_focus: bool | None = None,
    auto_play: bool | None = None,
    auto_save: str | None = None,
    class_name: str | None = None,
    color: str | None = None,
    content: str | None = None,
    content_editable: bool | Literal["inherit"] | Literal["plaintext-only"] | None = None,
    context_menu: str | None = None,
    controls: bool | None = None,
    controls_list: str | None = None,
    cross_origin: Literal["anonymous", "use-credentials", ""] | None = None,
    datatype: str | None = None,
    default_checked: bool | None = None,
    default_value: str | int | float | list[str] | None = None,
    dir: str | None = None,
    disable_picture_in_picture: bool | None = None,
    disable_remote_playback: bool | None = None,
    draggable: bool | None = None,
    enter_key_hint: (
        Literal[
            "enter",
            "done",
            "go",
            "next",
            "previous",
            "search",
            "send",
        ]
        | None
    ) = None,
    exportparts: str | None = None,
    height: int | float | str | None = None,
    hidden: bool | None = None,
    id: str | None = None,
    inert: bool | None = None,
    inlist: str | None = None,
    input_mode: (
        Literal[
            "none",
            "text",
            "tel",
            "url",
            "email",
            "numeric",
            "decimal",
            "search",
        ]
        | None
    ) = None,
    is_: str | None = None,
    item_id: str | None = None,
    item_prop: str | None = None,
    item_ref: str | None = None,
    item_scope: bool | None = None,
    item_type: str | None = None,
    lang: str | None = None,
    loop: bool | None = None,
    media_group: str | None = None,
    muted: bool | None = None,
    nonce: str | None = None,
    part: str | None = None,
    plays_inline: bool | None = None,
    popover: Literal["", "auto", "manual", "hint"] | None = None,
    popover_target: str | None = None,
    popover_target_action: Literal["toggle", "show", "hide"] | None = None,
    poster: str | None = None,
    prefix: str | None = None,
    preload: str | None = None,
    property: str | None = None,
    radio_group: str | None = None,
    rel: str | None = None,
    resource: str | None = None,
    results: int | float | None = None,
    rev: str | None = None,
    role: (
        Literal[
            "alert",
            "alertdialog",
            "application",
            "article",
            "banner",
            "button",
            "cell",
            "checkbox",
            "columnheader",
            "combobox",
            "complementary",
            "contentinfo",
            "definition",
            "dialog",
            "directory",
            "document",
            "feed",
            "figure",
            "form",
            "grid",
            "gridcell",
            "group",
            "heading",
            "img",
            "link",
            "list",
            "listbox",
            "listitem",
            "log",
            "main",
            "marquee",
            "math",
            "menu",
            "menubar",
            "menuitem",
            "menuitemcheckbox",
            "menuitemradio",
            "navigation",
            "none",
            "note",
            "option",
            "presentation",
            "progressbar",
            "radio",
            "radiogroup",
            "region",
            "row",
            "rowgroup",
            "rowheader",
            "scrollbar",
            "search",
            "searchbox",
            "separator",
            "slider",
            "spinbutton",
            "status",
            "switch",
            "tab",
            "table",
            "tablist",
            "tabpanel",
            "term",
            "textbox",
            "timer",
            "toolbar",
            "tooltip",
            "tree",
            "treegrid",
            "treeitem",
        ]
        | None
    ) = None,
    security: str | None = None,
    slot: str | None = None,
    spell_check: bool | None = None,
    src: str | None = None,
    style: Style | None = None,
    suppress_content_editable_warning: bool | None = None,
    suppress_hydration_warning: bool | None = None,
    tab_index: int | float | None = None,
    title: str | None = None,
    translate: Literal["yes", "no"] | None = None,
    typeof: str | None = None,
    unselectable: Literal["on", "off"] | None = None,
    vocab: str | None = None,
    width: int | float | str | None = None,
    on_blur: FocusEventHandler | None = None,
    on_change: EventHandler | None = None,
    on_click: MouseEventHandler | None = None,
    on_context_menu: MouseEventHandler | None = None,
    on_double_click: MouseEventHandler | None = None,
    on_drag: DragEventHandler | None = None,
    on_drag_end: DragEventHandler | None = None,
    on_drag_enter: DragEventHandler | None = None,
    on_drag_leave: DragEventHandler | None = None,
    on_drag_over: DragEventHandler | None = None,
    on_drag_start: DragEventHandler | None = None,
    on_drop: DragEventHandler | None = None,
    on_focus: FocusEventHandler | None = None,
    on_input: InputEventHandler | None = None,
    on_key_down: KeyboardEventHandler | None = None,
    on_key_up: KeyboardEventHandler | None = None,
    on_mouse_down: MouseEventHandler | None = None,
    on_mouse_enter: MouseEventHandler | None = None,
    on_mouse_leave: MouseEventHandler | None = None,
    on_mouse_move: MouseEventHandler | None = None,
    on_mouse_out: MouseEventHandler | None = None,
    on_mouse_over: MouseEventHandler | None = None,
    on_mouse_up: MouseEventHandler | None = None,
    on_scroll: UIEventHandler | None = None,
    on_submit: SubmitEventHandler | None = None,
    on_wheel: WheelEventHandler | None = None,
    data: Mapping[str, DataValue] | None = None,
) -> HtmlContainerElement:
    """<video />"""
    ...
