"""Generated CSS style type declarations.

Generated at: 2026-03-07T23:41:03.418Z
"""

from __future__ import annotations

import builtins
from dataclasses import dataclass
from typing import TYPE_CHECKING, Literal

from trellis.html._css_primitives import (
    CssAngle,
    CssColor,
    CssLength,
    CssPercent,
    CssTime,
    CssValue,
)

if TYPE_CHECKING:
    from trellis.html._style_runtime import Style

Length = CssLength
Percent = CssPercent
LengthPercentage = Length | Percent
TimeValue = CssTime
AngleValue = CssAngle
ColorValue = CssColor
Display = Literal["block", "inline", "inline-block", "flex", "grid", "none", "contents"]
Position = Literal["static", "relative", "absolute", "fixed", "sticky"]
Overflow = Literal["visible", "hidden", "clip", "scroll", "auto"]
TextAlign = Literal["left", "right", "center", "justify", "start", "end"]
FontWeight = int | Literal["normal"] | Literal["bold"] | Literal["lighter"] | Literal["bolder"]
FlexDirection = Literal["row", "row-reverse", "column", "column-reverse"]
FlexWrap = Literal["nowrap", "wrap", "wrap-reverse"]
JustifyContent = Literal[
    "flex-start",
    "flex-end",
    "center",
    "space-between",
    "space-around",
    "space-evenly",
    "start",
    "end",
]
AlignItems = Literal["stretch", "center", "start", "end", "flex-start", "flex-end", "baseline"]
WidthValue = (
    LengthPercentage
    | Literal["auto"]
    | Literal["min-content"]
    | Literal["max-content"]
    | Literal["fit-content"]
    | Literal["stretch"]
    | Literal["contain"]
    | CssValue
)
HeightValue = (
    LengthPercentage
    | Literal["auto"]
    | Literal["min-content"]
    | Literal["max-content"]
    | Literal["fit-content"]
    | Literal["stretch"]
    | Literal["contain"]
    | CssValue
)
BorderRadiusValue = LengthPercentage | CssValue
SpacingShorthand = LengthPercentage | CssValue
GapValue = LengthPercentage | Literal["normal"] | CssValue
LineHeightValue = LengthPercentage | float | Literal["normal"] | CssValue
ShadowValue = CssValue
TransformValue = CssValue
TransitionValue = CssValue
Opacity = float
ZIndex = int | Literal["auto"]
Orientation = Literal["portrait", "landscape"]
PrefersColorScheme = Literal["light", "dark"]
PrefersReducedMotion = Literal["reduce", "no-preference"]
PointerCapability = Literal["none", "coarse", "fine"]
HoverCapability = Literal["none", "hover"]


@dataclass(kw_only=True)
class _GeneratedStyleFields:
    accent_color: ColorValue | None = None
    align_content: CssValue | None = None
    align_items: AlignItems | None = None
    align_self: CssValue | None = None
    alignment_baseline: CssValue | None = None
    all: CssValue | None = None
    anchor_name: CssValue | None = None
    anchor_scope: CssValue | None = None
    animation: CssValue | None = None
    animation_composition: CssValue | None = None
    animation_delay: TimeValue | None = None
    animation_direction: CssValue | None = None
    animation_duration: TimeValue | None = None
    animation_fill_mode: CssValue | None = None
    animation_iteration_count: CssValue | None = None
    animation_name: CssValue | None = None
    animation_play_state: CssValue | None = None
    animation_range: CssValue | None = None
    animation_range_center: LengthPercentage | builtins.int | builtins.float | None = None
    animation_range_end: LengthPercentage | builtins.int | builtins.float | None = None
    animation_range_start: LengthPercentage | builtins.int | builtins.float | None = None
    animation_timeline: CssValue | None = None
    animation_timing_function: CssValue | None = None
    animation_trigger: CssValue | None = None
    appearance: CssValue | None = None
    aspect_ratio: CssValue | None = None
    backdrop_filter: CssValue | None = None
    backface_visibility: CssValue | None = None
    background: CssValue | None = None
    background_attachment: CssValue | None = None
    background_blend_mode: CssValue | None = None
    background_clip: CssValue | None = None
    background_color: ColorValue | None = None
    background_image: CssValue | None = None
    background_origin: CssValue | None = None
    background_position: CssValue | None = None
    background_position_block: LengthPercentage | builtins.int | builtins.float | None = None
    background_position_inline: LengthPercentage | builtins.int | builtins.float | None = None
    background_position_x: LengthPercentage | builtins.int | builtins.float | None = None
    background_position_y: LengthPercentage | builtins.int | builtins.float | None = None
    background_repeat: CssValue | None = None
    background_repeat_block: CssValue | None = None
    background_repeat_inline: CssValue | None = None
    background_repeat_x: CssValue | None = None
    background_repeat_y: CssValue | None = None
    background_size: CssValue | None = None
    background_tbd: CssValue | None = None
    baseline_shift: LengthPercentage | builtins.int | builtins.float | None = None
    baseline_source: CssValue | None = None
    block_ellipsis: CssValue | None = None
    block_size: CssValue | None = None
    block_step: CssValue | None = None
    block_step_align: CssValue | None = None
    block_step_insert: CssValue | None = None
    block_step_round: CssValue | None = None
    block_step_size: Length | builtins.int | builtins.float | None = None
    bookmark_label: CssValue | None = None
    bookmark_level: CssValue | None = None
    bookmark_state: CssValue | None = None
    border: ColorValue | CssValue | None = None
    border_block: CssValue | None = None
    border_block_clip: CssValue | None = None
    border_block_color: ColorValue | CssValue | None = None
    border_block_end: ColorValue | CssValue | None = None
    border_block_end_clip: LengthPercentage | builtins.int | builtins.float | None = None
    border_block_end_color: ColorValue | None = None
    border_block_end_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_block_end_style: CssValue | None = None
    border_block_end_width: WidthValue | builtins.int | builtins.float | None = None
    border_block_start: ColorValue | CssValue | None = None
    border_block_start_clip: LengthPercentage | builtins.int | builtins.float | None = None
    border_block_start_color: ColorValue | None = None
    border_block_start_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_block_start_style: CssValue | None = None
    border_block_start_width: WidthValue | builtins.int | builtins.float | None = None
    border_block_style: CssValue | None = None
    border_block_width: WidthValue | builtins.int | builtins.float | None = None
    border_bottom: ColorValue | CssValue | None = None
    border_bottom_clip: LengthPercentage | builtins.int | builtins.float | None = None
    border_bottom_color: ColorValue | None = None
    border_bottom_left_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_bottom_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_bottom_right_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_bottom_style: CssValue | None = None
    border_bottom_width: WidthValue | builtins.int | builtins.float | None = None
    border_boundary: CssValue | None = None
    border_clip: CssValue | None = None
    border_collapse: CssValue | None = None
    border_color: ColorValue | CssValue | None = None
    border_end_end_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_end_start_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_image: CssValue | None = None
    border_image_outset: Length | builtins.int | builtins.float | None = None
    border_image_repeat: CssValue | None = None
    border_image_slice: CssValue | None = None
    border_image_source: CssValue | None = None
    border_image_width: WidthValue | builtins.int | builtins.float | None = None
    border_inline: CssValue | None = None
    border_inline_clip: CssValue | None = None
    border_inline_color: ColorValue | CssValue | None = None
    border_inline_end: ColorValue | CssValue | None = None
    border_inline_end_clip: LengthPercentage | builtins.int | builtins.float | None = None
    border_inline_end_color: ColorValue | None = None
    border_inline_end_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_inline_end_style: CssValue | None = None
    border_inline_end_width: WidthValue | builtins.int | builtins.float | None = None
    border_inline_start: ColorValue | CssValue | None = None
    border_inline_start_clip: LengthPercentage | builtins.int | builtins.float | None = None
    border_inline_start_color: ColorValue | None = None
    border_inline_start_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_inline_start_style: CssValue | None = None
    border_inline_start_width: WidthValue | builtins.int | builtins.float | None = None
    border_inline_style: CssValue | None = None
    border_inline_width: WidthValue | builtins.int | builtins.float | None = None
    border_left: ColorValue | CssValue | None = None
    border_left_clip: LengthPercentage | builtins.int | builtins.float | None = None
    border_left_color: ColorValue | None = None
    border_left_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_left_style: CssValue | None = None
    border_left_width: WidthValue | builtins.int | builtins.float | None = None
    border_limit: LengthPercentage | builtins.int | builtins.float | None = None
    border_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_right: ColorValue | CssValue | None = None
    border_right_clip: LengthPercentage | builtins.int | builtins.float | None = None
    border_right_color: ColorValue | None = None
    border_right_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_right_style: CssValue | None = None
    border_right_width: WidthValue | builtins.int | builtins.float | None = None
    border_shape: CssValue | None = None
    border_spacing: Length | builtins.int | builtins.float | None = None
    border_start_end_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_start_start_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_style: CssValue | None = None
    border_top: ColorValue | CssValue | None = None
    border_top_clip: LengthPercentage | builtins.int | builtins.float | None = None
    border_top_color: ColorValue | None = None
    border_top_left_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_top_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_top_right_radius: BorderRadiusValue | builtins.int | builtins.float | None = None
    border_top_style: CssValue | None = None
    border_top_width: WidthValue | builtins.int | builtins.float | None = None
    border_width: WidthValue | builtins.int | builtins.float | None = None
    bottom: LengthPercentage | builtins.int | builtins.float | None = None
    box_decoration_break: CssValue | None = None
    box_shadow: ShadowValue | None = None
    box_shadow_blur: Length | builtins.int | builtins.float | None = None
    box_shadow_color: ColorValue | None = None
    box_shadow_offset: Length | builtins.int | builtins.float | None = None
    box_shadow_position: CssValue | None = None
    box_shadow_spread: Length | builtins.int | builtins.float | None = None
    box_sizing: CssValue | None = None
    box_snap: CssValue | None = None
    break_after: CssValue | None = None
    break_before: CssValue | None = None
    break_inside: CssValue | None = None
    caption_side: CssValue | None = None
    caret: CssValue | None = None
    caret_animation: CssValue | None = None
    caret_color: ColorValue | None = None
    caret_shape: CssValue | None = None
    clear: CssValue | None = None
    clip: CssValue | None = None
    clip_path: CssValue | None = None
    clip_rule: CssValue | None = None
    color: ColorValue | None = None
    color_adjust: CssValue | None = None
    color_interpolation: CssValue | None = None
    color_interpolation_filters: CssValue | None = None
    color_scheme: CssValue | None = None
    column_count: CssValue | None = None
    column_fill: CssValue | None = None
    column_gap: GapValue | builtins.int | builtins.float | None = None
    column_height: HeightValue | builtins.int | builtins.float | None = None
    column_rule: CssValue | None = None
    column_rule_break: CssValue | None = None
    column_rule_color: ColorValue | None = None
    column_rule_edge_inset: LengthPercentage | CssValue | builtins.int | builtins.float | None = (
        None
    )
    column_rule_edge_inset_end: LengthPercentage | builtins.int | builtins.float | None = None
    column_rule_edge_inset_start: LengthPercentage | builtins.int | builtins.float | None = None
    column_rule_inset: CssValue | None = None
    column_rule_inset_end: LengthPercentage | CssValue | builtins.int | builtins.float | None = None
    column_rule_inset_start: LengthPercentage | CssValue | builtins.int | builtins.float | None = (
        None
    )
    column_rule_interior_inset: (
        LengthPercentage | CssValue | builtins.int | builtins.float | None
    ) = None
    column_rule_interior_inset_end: LengthPercentage | builtins.int | builtins.float | None = None
    column_rule_interior_inset_start: LengthPercentage | builtins.int | builtins.float | None = None
    column_rule_style: CssValue | None = None
    column_rule_visibility_items: CssValue | None = None
    column_rule_width: WidthValue | builtins.int | builtins.float | None = None
    column_span: CssValue | None = None
    column_width: WidthValue | builtins.int | builtins.float | None = None
    column_wrap: CssValue | None = None
    columns: CssValue | None = None
    contain: CssValue | None = None
    contain_intrinsic_block_size: Length | builtins.int | builtins.float | None = None
    contain_intrinsic_height: HeightValue | builtins.int | builtins.float | None = None
    contain_intrinsic_inline_size: Length | builtins.int | builtins.float | None = None
    contain_intrinsic_size: Length | CssValue | builtins.int | builtins.float | None = None
    contain_intrinsic_width: WidthValue | builtins.int | builtins.float | None = None
    container: CssValue | None = None
    container_name: CssValue | None = None
    container_type: CssValue | None = None
    content: CssValue | None = None
    content_visibility: CssValue | None = None
    continue_: CssValue | None = None
    copy_into: CssValue | None = None
    corner: CssValue | None = None
    corner_block_end: CssValue | None = None
    corner_block_end_shape: CssValue | None = None
    corner_block_start: CssValue | None = None
    corner_block_start_shape: CssValue | None = None
    corner_bottom: CssValue | None = None
    corner_bottom_left: CssValue | None = None
    corner_bottom_left_shape: CssValue | None = None
    corner_bottom_right: CssValue | None = None
    corner_bottom_right_shape: CssValue | None = None
    corner_bottom_shape: CssValue | None = None
    corner_end_end: CssValue | None = None
    corner_end_end_shape: CssValue | None = None
    corner_end_start: CssValue | None = None
    corner_end_start_shape: CssValue | None = None
    corner_inline_end: CssValue | None = None
    corner_inline_end_shape: CssValue | None = None
    corner_inline_start: CssValue | None = None
    corner_inline_start_shape: CssValue | None = None
    corner_left: CssValue | None = None
    corner_left_shape: CssValue | None = None
    corner_right: CssValue | None = None
    corner_right_shape: CssValue | None = None
    corner_shape: CssValue | None = None
    corner_start_end: CssValue | None = None
    corner_start_end_shape: CssValue | None = None
    corner_start_start: CssValue | None = None
    corner_start_start_shape: CssValue | None = None
    corner_top: CssValue | None = None
    corner_top_left: CssValue | None = None
    corner_top_left_shape: CssValue | None = None
    corner_top_right: CssValue | None = None
    corner_top_right_shape: CssValue | None = None
    corner_top_shape: CssValue | None = None
    counter_increment: CssValue | None = None
    counter_reset: CssValue | None = None
    counter_set: CssValue | None = None
    cue: CssValue | None = None
    cue_after: CssValue | None = None
    cue_before: CssValue | None = None
    cursor: CssValue | None = None
    cx: LengthPercentage | builtins.int | builtins.float | None = None
    cy: LengthPercentage | builtins.int | builtins.float | None = None
    d: CssValue | None = None
    direction: CssValue | None = None
    display: Display | None = None
    dominant_baseline: CssValue | None = None
    dynamic_range_limit: CssValue | None = None
    empty_cells: CssValue | None = None
    event_trigger: CssValue | None = None
    event_trigger_name: CssValue | None = None
    event_trigger_source: CssValue | None = None
    field_sizing: CssValue | None = None
    fill: CssValue | None = None
    fill_break: CssValue | None = None
    fill_color: ColorValue | None = None
    fill_image: CssValue | None = None
    fill_opacity: CssValue | None = None
    fill_origin: CssValue | None = None
    fill_position: CssValue | None = None
    fill_repeat: CssValue | None = None
    fill_rule: CssValue | None = None
    fill_size: CssValue | None = None
    filter: CssValue | None = None
    flex: CssValue | None = None
    flex_basis: CssValue | None = None
    flex_direction: FlexDirection | None = None
    flex_flow: CssValue | None = None
    flex_grow: CssValue | None = None
    flex_shrink: CssValue | None = None
    flex_wrap: FlexWrap | None = None
    float: CssValue | None = None
    float_defer: CssValue | None = None
    float_offset: LengthPercentage | builtins.int | builtins.float | None = None
    float_reference: CssValue | None = None
    flood_color: ColorValue | None = None
    flood_opacity: CssValue | None = None
    flow_from: CssValue | None = None
    flow_into: CssValue | None = None
    flow_tolerance: LengthPercentage | builtins.int | builtins.float | None = None
    font: CssValue | None = None
    font_family: CssValue | None = None
    font_feature_settings: CssValue | None = None
    font_kerning: CssValue | None = None
    font_language_override: CssValue | None = None
    font_optical_sizing: CssValue | None = None
    font_palette: CssValue | None = None
    font_size: LengthPercentage | builtins.int | builtins.float | None = None
    font_size_adjust: CssValue | None = None
    font_stretch: CssValue | None = None
    font_style: AngleValue | None = None
    font_synthesis: CssValue | None = None
    font_synthesis_position: CssValue | None = None
    font_synthesis_small_caps: CssValue | None = None
    font_synthesis_style: CssValue | None = None
    font_synthesis_weight: CssValue | None = None
    font_variant: CssValue | None = None
    font_variant_alternates: CssValue | None = None
    font_variant_caps: CssValue | None = None
    font_variant_east_asian: CssValue | None = None
    font_variant_emoji: CssValue | None = None
    font_variant_ligatures: CssValue | None = None
    font_variant_numeric: CssValue | None = None
    font_variant_position: CssValue | None = None
    font_variation_settings: CssValue | None = None
    font_weight: FontWeight | None = None
    font_width: WidthValue | builtins.int | builtins.float | None = None
    footnote_display: CssValue | None = None
    footnote_policy: CssValue | None = None
    forced_color_adjust: CssValue | None = None
    gap: GapValue | builtins.int | builtins.float | None = None
    glyph_orientation_vertical: CssValue | None = None
    grid: CssValue | None = None
    grid_area: CssValue | None = None
    grid_auto_columns: CssValue | None = None
    grid_auto_flow: CssValue | None = None
    grid_auto_rows: CssValue | None = None
    grid_column: CssValue | None = None
    grid_column_end: CssValue | None = None
    grid_column_gap: GapValue | builtins.int | builtins.float | None = None
    grid_column_start: CssValue | None = None
    grid_gap: GapValue | builtins.int | builtins.float | None = None
    grid_row: CssValue | None = None
    grid_row_end: CssValue | None = None
    grid_row_gap: GapValue | builtins.int | builtins.float | None = None
    grid_row_start: CssValue | None = None
    grid_template: CssValue | None = None
    grid_template_areas: CssValue | None = None
    grid_template_columns: CssValue | None = None
    grid_template_rows: CssValue | None = None
    hanging_punctuation: CssValue | None = None
    height: HeightValue | builtins.int | builtins.float | None = None
    hyphenate_character: CssValue | None = None
    hyphenate_limit_chars: CssValue | None = None
    hyphenate_limit_last: CssValue | None = None
    hyphenate_limit_lines: CssValue | None = None
    hyphenate_limit_zone: LengthPercentage | builtins.int | builtins.float | None = None
    hyphens: CssValue | None = None
    image_animation: CssValue | None = None
    image_orientation: AngleValue | None = None
    image_rendering: CssValue | None = None
    image_resolution: CssValue | None = None
    initial_letter: CssValue | None = None
    initial_letter_align: CssValue | None = None
    initial_letter_wrap: LengthPercentage | builtins.int | builtins.float | None = None
    inline_size: CssValue | None = None
    inline_sizing: CssValue | None = None
    input_security: CssValue | None = None
    inset: SpacingShorthand | builtins.int | builtins.float | None = None
    inset_block: SpacingShorthand | builtins.int | builtins.float | None = None
    inset_block_end: SpacingShorthand | builtins.int | builtins.float | None = None
    inset_block_start: SpacingShorthand | builtins.int | builtins.float | None = None
    inset_inline: SpacingShorthand | builtins.int | builtins.float | None = None
    inset_inline_end: SpacingShorthand | builtins.int | builtins.float | None = None
    inset_inline_start: SpacingShorthand | builtins.int | builtins.float | None = None
    interactivity: CssValue | None = None
    interest_delay: CssValue | None = None
    interest_delay_end: TimeValue | None = None
    interest_delay_start: TimeValue | None = None
    interpolate_size: CssValue | None = None
    isolation: CssValue | None = None
    justify_content: JustifyContent | None = None
    justify_items: CssValue | None = None
    justify_self: CssValue | None = None
    left: LengthPercentage | builtins.int | builtins.float | None = None
    letter_spacing: LengthPercentage | builtins.int | builtins.float | None = None
    lighting_color: ColorValue | None = None
    line_break: CssValue | None = None
    line_clamp: CssValue | None = None
    line_fit_edge: CssValue | None = None
    line_grid: CssValue | None = None
    line_height: LineHeightValue | builtins.int | builtins.float | None = None
    line_height_step: Length | builtins.int | builtins.float | None = None
    line_padding: Length | builtins.int | builtins.float | None = None
    line_snap: CssValue | None = None
    link_parameters: CssValue | None = None
    list_style: CssValue | None = None
    list_style_image: CssValue | None = None
    list_style_position: CssValue | None = None
    list_style_type: CssValue | None = None
    margin: SpacingShorthand | builtins.int | builtins.float | None = None
    margin_block: SpacingShorthand | builtins.int | builtins.float | None = None
    margin_block_end: SpacingShorthand | builtins.int | builtins.float | None = None
    margin_block_start: SpacingShorthand | builtins.int | builtins.float | None = None
    margin_bottom: SpacingShorthand | builtins.int | builtins.float | None = None
    margin_break: SpacingShorthand | builtins.int | builtins.float | None = None
    margin_inline: SpacingShorthand | builtins.int | builtins.float | None = None
    margin_inline_end: SpacingShorthand | builtins.int | builtins.float | None = None
    margin_inline_start: SpacingShorthand | builtins.int | builtins.float | None = None
    margin_left: SpacingShorthand | builtins.int | builtins.float | None = None
    margin_right: SpacingShorthand | builtins.int | builtins.float | None = None
    margin_top: SpacingShorthand | builtins.int | builtins.float | None = None
    margin_trim: SpacingShorthand | builtins.int | builtins.float | None = None
    marker: CssValue | None = None
    marker_end: CssValue | None = None
    marker_mid: CssValue | None = None
    marker_side: CssValue | None = None
    marker_start: CssValue | None = None
    mask: CssValue | None = None
    mask_border: CssValue | None = None
    mask_border_mode: CssValue | None = None
    mask_border_outset: Length | builtins.int | builtins.float | None = None
    mask_border_repeat: CssValue | None = None
    mask_border_slice: CssValue | None = None
    mask_border_source: CssValue | None = None
    mask_border_width: WidthValue | builtins.int | builtins.float | None = None
    mask_clip: CssValue | None = None
    mask_composite: CssValue | None = None
    mask_image: CssValue | None = None
    mask_mode: CssValue | None = None
    mask_origin: CssValue | None = None
    mask_position: CssValue | None = None
    mask_repeat: CssValue | None = None
    mask_size: CssValue | None = None
    mask_type: CssValue | None = None
    math_depth: CssValue | None = None
    math_shift: CssValue | None = None
    math_style: CssValue | None = None
    max_block_size: CssValue | None = None
    max_height: HeightValue | builtins.int | builtins.float | None = None
    max_inline_size: CssValue | None = None
    max_lines: CssValue | None = None
    max_width: WidthValue | builtins.int | builtins.float | None = None
    min_block_size: CssValue | None = None
    min_height: HeightValue | builtins.int | builtins.float | None = None
    min_inline_size: CssValue | None = None
    min_intrinsic_sizing: CssValue | None = None
    min_width: WidthValue | builtins.int | builtins.float | None = None
    mix_blend_mode: CssValue | None = None
    nav_down: CssValue | None = None
    nav_left: CssValue | None = None
    nav_right: CssValue | None = None
    nav_up: CssValue | None = None
    object_fit: CssValue | None = None
    object_position: CssValue | None = None
    object_view_box: CssValue | None = None
    offset: CssValue | None = None
    offset_anchor: CssValue | None = None
    offset_distance: LengthPercentage | builtins.int | builtins.float | None = None
    offset_path: CssValue | None = None
    offset_position: CssValue | None = None
    offset_rotate: AngleValue | None = None
    opacity: builtins.float | None = None
    order: CssValue | None = None
    orphans: CssValue | None = None
    outline: CssValue | None = None
    outline_color: ColorValue | None = None
    outline_offset: Length | builtins.int | builtins.float | None = None
    outline_style: CssValue | None = None
    outline_width: WidthValue | builtins.int | builtins.float | None = None
    overflow: Overflow | CssValue | None = None
    overflow_anchor: Overflow | None = None
    overflow_block: Overflow | None = None
    overflow_clip_margin: Overflow | CssValue | builtins.int | builtins.float | None = None
    overflow_clip_margin_block: Overflow | CssValue | builtins.int | builtins.float | None = None
    overflow_clip_margin_block_end: Overflow | builtins.int | builtins.float | None = None
    overflow_clip_margin_block_start: Overflow | builtins.int | builtins.float | None = None
    overflow_clip_margin_bottom: Overflow | builtins.int | builtins.float | None = None
    overflow_clip_margin_inline: Overflow | CssValue | builtins.int | builtins.float | None = None
    overflow_clip_margin_inline_end: Overflow | builtins.int | builtins.float | None = None
    overflow_clip_margin_inline_start: Overflow | builtins.int | builtins.float | None = None
    overflow_clip_margin_left: Overflow | builtins.int | builtins.float | None = None
    overflow_clip_margin_right: Overflow | builtins.int | builtins.float | None = None
    overflow_clip_margin_top: Overflow | builtins.int | builtins.float | None = None
    overflow_inline: Overflow | None = None
    overflow_wrap: Overflow | None = None
    overflow_x: Overflow | None = None
    overflow_y: Overflow | None = None
    overlay: CssValue | None = None
    overscroll_behavior: CssValue | None = None
    overscroll_behavior_block: CssValue | None = None
    overscroll_behavior_inline: CssValue | None = None
    overscroll_behavior_x: CssValue | None = None
    overscroll_behavior_y: CssValue | None = None
    padding: SpacingShorthand | builtins.int | builtins.float | None = None
    padding_block: SpacingShorthand | builtins.int | builtins.float | None = None
    padding_block_end: SpacingShorthand | builtins.int | builtins.float | None = None
    padding_block_start: SpacingShorthand | builtins.int | builtins.float | None = None
    padding_bottom: SpacingShorthand | builtins.int | builtins.float | None = None
    padding_inline: SpacingShorthand | builtins.int | builtins.float | None = None
    padding_inline_end: SpacingShorthand | builtins.int | builtins.float | None = None
    padding_inline_start: SpacingShorthand | builtins.int | builtins.float | None = None
    padding_left: SpacingShorthand | builtins.int | builtins.float | None = None
    padding_right: SpacingShorthand | builtins.int | builtins.float | None = None
    padding_top: SpacingShorthand | builtins.int | builtins.float | None = None
    page: CssValue | None = None
    page_break_after: CssValue | None = None
    page_break_before: CssValue | None = None
    page_break_inside: CssValue | None = None
    paint_order: CssValue | None = None
    pause: CssValue | None = None
    pause_after: TimeValue | None = None
    pause_before: TimeValue | None = None
    perspective: Length | builtins.int | builtins.float | None = None
    perspective_origin: CssValue | None = None
    place_content: CssValue | None = None
    place_items: CssValue | None = None
    place_self: CssValue | None = None
    pointer_events: CssValue | None = None
    pointer_timeline: CssValue | None = None
    pointer_timeline_axis: CssValue | None = None
    pointer_timeline_name: CssValue | None = None
    position: Position | None = None
    position_anchor: CssValue | None = None
    position_area: CssValue | None = None
    position_try: CssValue | None = None
    position_try_fallbacks: CssValue | None = None
    position_try_order: CssValue | None = None
    position_visibility: CssValue | None = None
    print_color_adjust: CssValue | None = None
    quotes: CssValue | None = None
    r: LengthPercentage | builtins.int | builtins.float | None = None
    reading_flow: CssValue | None = None
    reading_order: CssValue | None = None
    region_fragment: CssValue | None = None
    resize: CssValue | None = None
    rest: CssValue | None = None
    rest_after: TimeValue | None = None
    rest_before: TimeValue | None = None
    right: LengthPercentage | builtins.int | builtins.float | None = None
    rotate: AngleValue | None = None
    row_gap: GapValue | builtins.int | builtins.float | None = None
    row_rule: CssValue | None = None
    row_rule_break: CssValue | None = None
    row_rule_color: ColorValue | None = None
    row_rule_edge_inset: LengthPercentage | CssValue | builtins.int | builtins.float | None = None
    row_rule_edge_inset_end: LengthPercentage | builtins.int | builtins.float | None = None
    row_rule_edge_inset_start: LengthPercentage | builtins.int | builtins.float | None = None
    row_rule_inset: CssValue | None = None
    row_rule_inset_end: LengthPercentage | CssValue | builtins.int | builtins.float | None = None
    row_rule_inset_start: LengthPercentage | CssValue | builtins.int | builtins.float | None = None
    row_rule_interior_inset: LengthPercentage | CssValue | builtins.int | builtins.float | None = (
        None
    )
    row_rule_interior_inset_end: LengthPercentage | builtins.int | builtins.float | None = None
    row_rule_interior_inset_start: LengthPercentage | builtins.int | builtins.float | None = None
    row_rule_style: CssValue | None = None
    row_rule_visibility_items: CssValue | None = None
    row_rule_width: WidthValue | builtins.int | builtins.float | None = None
    ruby_align: CssValue | None = None
    ruby_merge: CssValue | None = None
    ruby_overhang: CssValue | None = None
    ruby_position: CssValue | None = None
    rule: CssValue | None = None
    rule_break: CssValue | None = None
    rule_color: ColorValue | CssValue | None = None
    rule_edge_inset: CssValue | None = None
    rule_inset: CssValue | None = None
    rule_inset_end: CssValue | None = None
    rule_inset_start: CssValue | None = None
    rule_interior_inset: CssValue | None = None
    rule_overlap: CssValue | None = None
    rule_style: CssValue | None = None
    rule_visibility_items: CssValue | None = None
    rule_width: WidthValue | builtins.int | builtins.float | None = None
    rx: LengthPercentage | builtins.int | builtins.float | None = None
    ry: LengthPercentage | builtins.int | builtins.float | None = None
    scale: CssValue | None = None
    scroll_behavior: CssValue | None = None
    scroll_initial_target: CssValue | None = None
    scroll_margin: Length | CssValue | builtins.int | builtins.float | None = None
    scroll_margin_block: Length | CssValue | builtins.int | builtins.float | None = None
    scroll_margin_block_end: Length | builtins.int | builtins.float | None = None
    scroll_margin_block_start: Length | builtins.int | builtins.float | None = None
    scroll_margin_bottom: Length | builtins.int | builtins.float | None = None
    scroll_margin_inline: Length | CssValue | builtins.int | builtins.float | None = None
    scroll_margin_inline_end: Length | builtins.int | builtins.float | None = None
    scroll_margin_inline_start: Length | builtins.int | builtins.float | None = None
    scroll_margin_left: Length | builtins.int | builtins.float | None = None
    scroll_margin_right: Length | builtins.int | builtins.float | None = None
    scroll_margin_top: Length | builtins.int | builtins.float | None = None
    scroll_marker_group: CssValue | None = None
    scroll_padding: LengthPercentage | CssValue | builtins.int | builtins.float | None = None
    scroll_padding_block: LengthPercentage | CssValue | builtins.int | builtins.float | None = None
    scroll_padding_block_end: LengthPercentage | builtins.int | builtins.float | None = None
    scroll_padding_block_start: LengthPercentage | builtins.int | builtins.float | None = None
    scroll_padding_bottom: LengthPercentage | builtins.int | builtins.float | None = None
    scroll_padding_inline: LengthPercentage | CssValue | builtins.int | builtins.float | None = None
    scroll_padding_inline_end: LengthPercentage | builtins.int | builtins.float | None = None
    scroll_padding_inline_start: LengthPercentage | builtins.int | builtins.float | None = None
    scroll_padding_left: LengthPercentage | builtins.int | builtins.float | None = None
    scroll_padding_right: LengthPercentage | builtins.int | builtins.float | None = None
    scroll_padding_top: LengthPercentage | builtins.int | builtins.float | None = None
    scroll_snap_align: CssValue | None = None
    scroll_snap_stop: CssValue | None = None
    scroll_snap_type: CssValue | None = None
    scroll_target_group: CssValue | None = None
    scroll_timeline: CssValue | None = None
    scroll_timeline_axis: CssValue | None = None
    scroll_timeline_name: CssValue | None = None
    scrollbar_color: ColorValue | None = None
    scrollbar_gutter: CssValue | None = None
    scrollbar_width: WidthValue | builtins.int | builtins.float | None = None
    shape_image_threshold: CssValue | None = None
    shape_inside: CssValue | None = None
    shape_margin: LengthPercentage | builtins.int | builtins.float | None = None
    shape_outside: CssValue | None = None
    shape_padding: LengthPercentage | builtins.int | builtins.float | None = None
    shape_rendering: CssValue | None = None
    shape_subtract: CssValue | None = None
    slider_orientation: CssValue | None = None
    spatial_navigation_action: CssValue | None = None
    spatial_navigation_contain: CssValue | None = None
    spatial_navigation_function: CssValue | None = None
    speak: CssValue | None = None
    speak_as: CssValue | None = None
    stop_color: ColorValue | None = None
    stop_opacity: CssValue | None = None
    string_set: CssValue | None = None
    stroke: CssValue | None = None
    stroke_align: CssValue | None = None
    stroke_alignment: CssValue | None = None
    stroke_break: CssValue | None = None
    stroke_color: ColorValue | None = None
    stroke_dash_corner: Length | builtins.int | builtins.float | None = None
    stroke_dash_justify: CssValue | None = None
    stroke_dashadjust: CssValue | None = None
    stroke_dasharray: LengthPercentage | builtins.int | builtins.float | None = None
    stroke_dashcorner: Length | builtins.int | builtins.float | None = None
    stroke_dashoffset: LengthPercentage | builtins.int | builtins.float | None = None
    stroke_image: CssValue | None = None
    stroke_linecap: CssValue | None = None
    stroke_linejoin: CssValue | None = None
    stroke_miterlimit: CssValue | None = None
    stroke_opacity: CssValue | None = None
    stroke_origin: CssValue | None = None
    stroke_position: CssValue | None = None
    stroke_repeat: CssValue | None = None
    stroke_size: CssValue | None = None
    stroke_width: WidthValue | builtins.int | builtins.float | None = None
    tab_size: Length | builtins.int | builtins.float | None = None
    table_layout: CssValue | None = None
    text_align: TextAlign | CssValue | None = None
    text_align_all: CssValue | None = None
    text_align_last: CssValue | None = None
    text_anchor: CssValue | None = None
    text_autospace: CssValue | None = None
    text_box: CssValue | None = None
    text_box_edge: CssValue | None = None
    text_box_trim: CssValue | None = None
    text_combine_upright: CssValue | None = None
    text_decoration: CssValue | None = None
    text_decoration_color: ColorValue | None = None
    text_decoration_inset: Length | builtins.int | builtins.float | None = None
    text_decoration_line: CssValue | None = None
    text_decoration_skip: CssValue | None = None
    text_decoration_skip_box: CssValue | None = None
    text_decoration_skip_ink: CssValue | None = None
    text_decoration_skip_self: CssValue | None = None
    text_decoration_skip_spaces: CssValue | None = None
    text_decoration_style: CssValue | None = None
    text_decoration_thickness: LengthPercentage | builtins.int | builtins.float | None = None
    text_emphasis: CssValue | None = None
    text_emphasis_color: ColorValue | None = None
    text_emphasis_position: CssValue | None = None
    text_emphasis_skip: CssValue | None = None
    text_emphasis_style: CssValue | None = None
    text_group_align: CssValue | None = None
    text_indent: LengthPercentage | builtins.int | builtins.float | None = None
    text_justify: CssValue | None = None
    text_orientation: CssValue | None = None
    text_overflow: CssValue | None = None
    text_rendering: CssValue | None = None
    text_shadow: CssValue | None = None
    text_size_adjust: CssValue | None = None
    text_spacing: CssValue | None = None
    text_spacing_trim: CssValue | None = None
    text_transform: CssValue | None = None
    text_underline_offset: LengthPercentage | builtins.int | builtins.float | None = None
    text_underline_position: CssValue | None = None
    text_wrap: CssValue | None = None
    text_wrap_mode: CssValue | None = None
    text_wrap_style: CssValue | None = None
    timeline_scope: CssValue | None = None
    timeline_trigger: CssValue | None = None
    timeline_trigger_activation_range: CssValue | None = None
    timeline_trigger_activation_range_end: (
        LengthPercentage | builtins.int | builtins.float | None
    ) = None
    timeline_trigger_activation_range_start: (
        LengthPercentage | builtins.int | builtins.float | None
    ) = None
    timeline_trigger_active_range: CssValue | None = None
    timeline_trigger_active_range_end: LengthPercentage | builtins.int | builtins.float | None = (
        None
    )
    timeline_trigger_active_range_start: LengthPercentage | builtins.int | builtins.float | None = (
        None
    )
    timeline_trigger_name: CssValue | None = None
    timeline_trigger_source: CssValue | None = None
    top: LengthPercentage | builtins.int | builtins.float | None = None
    touch_action: CssValue | None = None
    transform: TransformValue | None = None
    transform_box: CssValue | None = None
    transform_origin: LengthPercentage | builtins.int | builtins.float | None = None
    transform_style: CssValue | None = None
    transition: TransitionValue | None = None
    transition_behavior: TransitionValue | None = None
    transition_delay: TransitionValue | None = None
    transition_duration: TransitionValue | None = None
    transition_property: TransitionValue | None = None
    transition_timing_function: TransitionValue | None = None
    translate: LengthPercentage | builtins.int | builtins.float | None = None
    trigger_scope: CssValue | None = None
    unicode_bidi: CssValue | None = None
    user_select: CssValue | None = None
    vector_effect: CssValue | None = None
    vertical_align: CssValue | None = None
    view_timeline: CssValue | None = None
    view_timeline_axis: CssValue | None = None
    view_timeline_inset: LengthPercentage | builtins.int | builtins.float | None = None
    view_timeline_name: CssValue | None = None
    view_transition_class: CssValue | None = None
    view_transition_group: CssValue | None = None
    view_transition_name: CssValue | None = None
    view_transition_scope: CssValue | None = None
    visibility: CssValue | None = None
    voice_balance: CssValue | None = None
    voice_duration: TimeValue | None = None
    voice_family: CssValue | None = None
    voice_pitch: CssValue | None = None
    voice_range: CssValue | None = None
    voice_rate: CssValue | None = None
    voice_stress: CssValue | None = None
    voice_volume: CssValue | None = None
    white_space: CssValue | None = None
    white_space_collapse: CssValue | None = None
    white_space_trim: CssValue | None = None
    widows: CssValue | None = None
    width: WidthValue | builtins.int | builtins.float | None = None
    will_change: CssValue | None = None
    word_break: CssValue | None = None
    word_space_transform: CssValue | None = None
    word_spacing: LengthPercentage | builtins.int | builtins.float | None = None
    word_wrap: CssValue | None = None
    wrap_after: CssValue | None = None
    wrap_before: CssValue | None = None
    wrap_flow: CssValue | None = None
    wrap_inside: CssValue | None = None
    wrap_through: CssValue | None = None
    writing_mode: CssValue | None = None
    x: LengthPercentage | builtins.int | builtins.float | None = None
    y: LengthPercentage | builtins.int | builtins.float | None = None
    z_index: builtins.int | Literal["auto"] | None = None
    zoom: CssValue | None = None


@dataclass(frozen=True, kw_only=True)
class MediaRule:
    style: Style
    any_hover: HoverCapability | None = None
    any_pointer: PointerCapability | None = None
    aspect_ratio: CssValue | None = None
    color: CssValue | None = None
    color_gamut: CssValue | None = None
    color_index: CssValue | None = None
    device_aspect_ratio: CssValue | None = None
    device_height: CssValue | None = None
    device_width: CssValue | None = None
    display_mode: CssValue | None = None
    dynamic_range: CssValue | None = None
    environment_blending: CssValue | None = None
    forced_colors: CssValue | None = None
    grid: CssValue | None = None
    height: CssValue | None = None
    horizontal_viewport_segments: CssValue | None = None
    hover: HoverCapability | None = None
    inverted_colors: CssValue | None = None
    max_height: Length | None = None
    max_width: Length | None = None
    min_height: Length | None = None
    min_width: Length | None = None
    monochrome: CssValue | None = None
    nav_controls: CssValue | None = None
    orientation: Orientation | None = None
    overflow_block: CssValue | None = None
    overflow_inline: CssValue | None = None
    pointer: PointerCapability | None = None
    prefers_color_scheme: PrefersColorScheme | None = None
    prefers_contrast: CssValue | None = None
    prefers_reduced_data: CssValue | None = None
    prefers_reduced_motion: PrefersReducedMotion | None = None
    prefers_reduced_transparency: CssValue | None = None
    resolution: CssValue | None = None
    scan: CssValue | None = None
    scripting: CssValue | None = None
    shape: CssValue | None = None
    update: CssValue | None = None
    vertical_viewport_segments: CssValue | None = None
    video_color_gamut: CssValue | None = None
    video_dynamic_range: CssValue | None = None
    width: CssValue | None = None
    query: str | None = None
