"""Generated HTML table content runtime wrappers.

Internal codegen artifact for trellis.html.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements

Generated by html-codegen.
"""

from __future__ import annotations

from trellis.html._runtime_factory import create_html_element

__all__ = [
    "Caption",
    "Col",
    "Colgroup",
    "Table",
    "Tbody",
    "Td",
    "Tfoot",
    "Th",
    "Thead",
    "Tr",
]

Caption = create_html_element(
    "caption",
    component_name="Caption",
    export_name="Caption",
    is_container=True,
    doc="Generated wrapper for `<caption>`.\n\nMaps to the standard HTML `<caption>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption",
)
Col = create_html_element(
    "col",
    component_name="Col",
    export_name="Col",
    doc="Generated wrapper for `<col>`.\n\nMaps to the standard HTML `<col>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col",
)
Colgroup = create_html_element(
    "colgroup",
    component_name="Colgroup",
    export_name="Colgroup",
    is_container=True,
    doc="Generated wrapper for `<colgroup>`.\n\nMaps to the standard HTML `<colgroup>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/colgroup",
)
Table = create_html_element(
    "table",
    component_name="Table",
    export_name="Table",
    is_container=True,
    doc="Generated wrapper for `<table>`.\n\nMaps to the standard HTML `<table>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table",
)
Tbody = create_html_element(
    "tbody",
    component_name="Tbody",
    export_name="Tbody",
    is_container=True,
    doc="Generated wrapper for `<tbody>`.\n\nMaps to the standard HTML `<tbody>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody",
)
Td = create_html_element(
    "td",
    component_name="Td",
    export_name="Td",
    is_container=True,
    doc="Generated wrapper for `<td>`.\n\nMaps to the standard HTML `<td>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td",
)
Tfoot = create_html_element(
    "tfoot",
    component_name="Tfoot",
    export_name="Tfoot",
    is_container=True,
    doc="Generated wrapper for `<tfoot>`.\n\nMaps to the standard HTML `<tfoot>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot",
)
Th = create_html_element(
    "th",
    component_name="Th",
    export_name="Th",
    is_container=True,
    doc="Generated wrapper for `<th>`.\n\nMaps to the standard HTML `<th>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th",
)
Thead = create_html_element(
    "thead",
    component_name="Thead",
    export_name="Thead",
    is_container=True,
    doc="Generated wrapper for `<thead>`.\n\nMaps to the standard HTML `<thead>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead",
)
Tr = create_html_element(
    "tr",
    component_name="Tr",
    export_name="Tr",
    is_container=True,
    doc="Generated wrapper for `<tr>`.\n\nMaps to the standard HTML `<tr>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr",
)
