"""Generated HTML interactive elements runtime wrappers.

Internal codegen artifact for trellis.html.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements

Generated by html-codegen.
"""

from __future__ import annotations

from trellis.html._runtime_factory import create_html_element

__all__ = []

_A = create_html_element(
    "a",
    component_name="A",
    export_name="_A",
    is_container=True,
    doc="Generated internal wrapper for `<a>`.\n\nMaps to the standard HTML `<a>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a",
)
