"""Generated HTML obsolete elements runtime wrappers.

Internal codegen artifact for trellis.html.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements

Generated by html-codegen.
"""

from __future__ import annotations

from trellis.html._runtime_factory import create_html_element

__all__ = [
    "Keygen",
    "Menuitem",
]

Keygen = create_html_element(
    "keygen",
    component_name="Keygen",
    export_name="Keygen",
    doc="Generated wrapper for `<keygen>`.\n\nMaps to the standard HTML `<keygen>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/keygen",
)
Menuitem = create_html_element(
    "menuitem",
    component_name="Menuitem",
    export_name="Menuitem",
    doc="Generated wrapper for `<menuitem>`.\n\nMaps to the standard HTML `<menuitem>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem",
)
