"""Generated HTML lists runtime wrappers.

Internal codegen artifact for trellis.html.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements

Generated by html-codegen.
"""

from __future__ import annotations

from trellis.html._runtime_factory import create_html_element

__all__ = [
    "Dd",
    "Dl",
    "Dt",
    "Li",
    "Menu",
    "Ol",
    "Ul",
]

Dd = create_html_element(
    "dd",
    component_name="Dd",
    export_name="Dd",
    is_container=True,
    doc="Generated wrapper for `<dd>`.\n\nMaps to the standard HTML `<dd>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dd",
)
Dl = create_html_element(
    "dl",
    component_name="Dl",
    export_name="Dl",
    is_container=True,
    doc="Generated wrapper for `<dl>`.\n\nMaps to the standard HTML `<dl>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl",
)
Dt = create_html_element(
    "dt",
    component_name="Dt",
    export_name="Dt",
    is_container=True,
    doc="Generated wrapper for `<dt>`.\n\nMaps to the standard HTML `<dt>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dt",
)
Li = create_html_element(
    "li",
    component_name="Li",
    export_name="Li",
    is_container=True,
    doc="Generated wrapper for `<li>`.\n\nMaps to the standard HTML `<li>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li",
)
Menu = create_html_element(
    "menu",
    component_name="Menu",
    export_name="Menu",
    is_container=True,
    doc="Generated wrapper for `<menu>`.\n\nMaps to the standard HTML `<menu>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu",
)
Ol = create_html_element(
    "ol",
    component_name="Ol",
    export_name="Ol",
    is_container=True,
    doc="Generated wrapper for `<ol>`.\n\nMaps to the standard HTML `<ol>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol",
)
Ul = create_html_element(
    "ul",
    component_name="Ul",
    export_name="Ul",
    is_container=True,
    doc="Generated wrapper for `<ul>`.\n\nMaps to the standard HTML `<ul>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul",
)
