"""Generated HTML interactive elements elements.

Generated at: 2026-03-07T23:41:03.418Z
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Literal, overload

from trellis.core.rendering.element import Element
from trellis.html._generated_attribute_types import (
    AriaAutocomplete,
    AriaChecked,
    AriaCurrent,
    AriaDropeffect,
    AriaHaspopup,
    AriaInvalid,
    AriaLive,
    AriaOrientation,
    AriaPressed,
    AriaRelevant,
    AriaSort,
    AutoCapitalize,
    ContentEditable,
    EnterKeyHint,
    InputMode,
    Popover,
    PopoverTargetAction,
    ReferrerPolicy,
    Role,
    Translate,
    Unselectable,
)
from trellis.html._generated_events import (
    DragEventHandler,
    EventHandler,
    FocusEventHandler,
    InputEventHandler,
    KeyboardEventHandler,
    MouseEventHandler,
    SubmitEventHandler,
    UIEventHandler,
    WheelEventHandler,
)
from trellis.html._style_runtime import StyleInput
from trellis.html.base import HtmlContainerElement, html_element

__all__ = [
    "_A",
]

DataValue = str | int | float | bool | None


@overload
def _A(
    inner_text: str,
    /,
    *,
    about: str | None = None,
    access_key: str | None = None,
    aria_activedescendant: str | None = None,
    aria_atomic: bool | None = None,
    aria_autocomplete: AriaAutocomplete | None = None,
    aria_braillelabel: str | None = None,
    aria_brailleroledescription: str | None = None,
    aria_busy: bool | None = None,
    aria_checked: AriaChecked | None = None,
    aria_colcount: int | float | None = None,
    aria_colindex: int | float | None = None,
    aria_colindextext: str | None = None,
    aria_colspan: int | float | None = None,
    aria_controls: str | None = None,
    aria_current: AriaCurrent | None = None,
    aria_describedby: str | None = None,
    aria_description: str | None = None,
    aria_details: str | None = None,
    aria_disabled: bool | None = None,
    aria_dropeffect: AriaDropeffect | None = None,
    aria_errormessage: str | None = None,
    aria_expanded: bool | None = None,
    aria_flowto: str | None = None,
    aria_grabbed: bool | None = None,
    aria_haspopup: AriaHaspopup | None = None,
    aria_hidden: bool | None = None,
    aria_invalid: AriaInvalid | None = None,
    aria_keyshortcuts: str | None = None,
    aria_label: str | None = None,
    aria_labelledby: str | None = None,
    aria_level: int | float | None = None,
    aria_live: AriaLive | None = None,
    aria_modal: bool | None = None,
    aria_multiline: bool | None = None,
    aria_multiselectable: bool | None = None,
    aria_orientation: AriaOrientation | None = None,
    aria_owns: str | None = None,
    aria_placeholder: str | None = None,
    aria_posinset: int | float | None = None,
    aria_pressed: AriaPressed | None = None,
    aria_readonly: bool | None = None,
    aria_relevant: AriaRelevant | None = None,
    aria_required: bool | None = None,
    aria_roledescription: str | None = None,
    aria_rowcount: int | float | None = None,
    aria_rowindex: int | float | None = None,
    aria_rowindextext: str | None = None,
    aria_rowspan: int | float | None = None,
    aria_selected: bool | None = None,
    aria_setsize: int | float | None = None,
    aria_sort: AriaSort | None = None,
    aria_valuemax: int | float | None = None,
    aria_valuemin: int | float | None = None,
    aria_valuenow: int | float | None = None,
    aria_valuetext: str | None = None,
    auto_capitalize: AutoCapitalize | None = None,
    auto_correct: str | None = None,
    auto_focus: bool | None = None,
    auto_save: str | None = None,
    class_name: str | None = None,
    color: str | None = None,
    content: str | None = None,
    content_editable: ContentEditable | None = None,
    context_menu: str | None = None,
    datatype: str | None = None,
    default_checked: bool | None = None,
    default_value: str | int | float | list[str] | None = None,
    dir: str | None = None,
    download: str | bool | None = None,
    draggable: bool | None = None,
    enter_key_hint: EnterKeyHint | None = None,
    exportparts: str | None = None,
    hidden: bool | None = None,
    href: str | None = None,
    href_lang: str | None = None,
    id: str | None = None,
    inert: bool | None = None,
    inlist: str | None = None,
    input_mode: InputMode | None = None,
    is_: str | None = None,
    item_id: str | None = None,
    item_prop: str | None = None,
    item_ref: str | None = None,
    item_scope: bool | None = None,
    item_type: str | None = None,
    lang: str | None = None,
    media: str | None = None,
    nonce: str | None = None,
    part: str | None = None,
    ping: str | None = None,
    popover: Popover | None = None,
    popover_target: str | None = None,
    popover_target_action: PopoverTargetAction | None = None,
    prefix: str | None = None,
    property: str | None = None,
    radio_group: str | None = None,
    referrer_policy: ReferrerPolicy | None = None,
    rel: str | None = None,
    resource: str | None = None,
    results: int | float | None = None,
    rev: str | None = None,
    role: Role | None = None,
    security: str | None = None,
    slot: str | None = None,
    spell_check: bool | None = None,
    style: StyleInput | None = None,
    suppress_content_editable_warning: bool | None = None,
    suppress_hydration_warning: bool | None = None,
    tab_index: int | float | None = None,
    target: Literal["_self", "_blank", "_parent", "_top"] | None = None,
    title: str | None = None,
    translate: Translate | None = None,
    type: str | None = None,
    typeof: str | None = None,
    unselectable: Unselectable | None = None,
    vocab: str | None = None,
    on_blur: FocusEventHandler | None = None,
    on_change: EventHandler | None = None,
    on_click: MouseEventHandler | None = None,
    on_context_menu: MouseEventHandler | None = None,
    on_double_click: MouseEventHandler | None = None,
    on_drag: DragEventHandler | None = None,
    on_drag_end: DragEventHandler | None = None,
    on_drag_enter: DragEventHandler | None = None,
    on_drag_leave: DragEventHandler | None = None,
    on_drag_over: DragEventHandler | None = None,
    on_drag_start: DragEventHandler | None = None,
    on_drop: DragEventHandler | None = None,
    on_focus: FocusEventHandler | None = None,
    on_input: InputEventHandler | None = None,
    on_key_down: KeyboardEventHandler | None = None,
    on_key_up: KeyboardEventHandler | None = None,
    on_mouse_down: MouseEventHandler | None = None,
    on_mouse_enter: MouseEventHandler | None = None,
    on_mouse_leave: MouseEventHandler | None = None,
    on_mouse_move: MouseEventHandler | None = None,
    on_mouse_out: MouseEventHandler | None = None,
    on_mouse_over: MouseEventHandler | None = None,
    on_mouse_up: MouseEventHandler | None = None,
    on_scroll: UIEventHandler | None = None,
    on_submit: SubmitEventHandler | None = None,
    on_wheel: WheelEventHandler | None = None,
    data: Mapping[str, DataValue] | None = None,
) -> Element: ...


@overload
def _A(
    *,
    about: str | None = None,
    access_key: str | None = None,
    aria_activedescendant: str | None = None,
    aria_atomic: bool | None = None,
    aria_autocomplete: AriaAutocomplete | None = None,
    aria_braillelabel: str | None = None,
    aria_brailleroledescription: str | None = None,
    aria_busy: bool | None = None,
    aria_checked: AriaChecked | None = None,
    aria_colcount: int | float | None = None,
    aria_colindex: int | float | None = None,
    aria_colindextext: str | None = None,
    aria_colspan: int | float | None = None,
    aria_controls: str | None = None,
    aria_current: AriaCurrent | None = None,
    aria_describedby: str | None = None,
    aria_description: str | None = None,
    aria_details: str | None = None,
    aria_disabled: bool | None = None,
    aria_dropeffect: AriaDropeffect | None = None,
    aria_errormessage: str | None = None,
    aria_expanded: bool | None = None,
    aria_flowto: str | None = None,
    aria_grabbed: bool | None = None,
    aria_haspopup: AriaHaspopup | None = None,
    aria_hidden: bool | None = None,
    aria_invalid: AriaInvalid | None = None,
    aria_keyshortcuts: str | None = None,
    aria_label: str | None = None,
    aria_labelledby: str | None = None,
    aria_level: int | float | None = None,
    aria_live: AriaLive | None = None,
    aria_modal: bool | None = None,
    aria_multiline: bool | None = None,
    aria_multiselectable: bool | None = None,
    aria_orientation: AriaOrientation | None = None,
    aria_owns: str | None = None,
    aria_placeholder: str | None = None,
    aria_posinset: int | float | None = None,
    aria_pressed: AriaPressed | None = None,
    aria_readonly: bool | None = None,
    aria_relevant: AriaRelevant | None = None,
    aria_required: bool | None = None,
    aria_roledescription: str | None = None,
    aria_rowcount: int | float | None = None,
    aria_rowindex: int | float | None = None,
    aria_rowindextext: str | None = None,
    aria_rowspan: int | float | None = None,
    aria_selected: bool | None = None,
    aria_setsize: int | float | None = None,
    aria_sort: AriaSort | None = None,
    aria_valuemax: int | float | None = None,
    aria_valuemin: int | float | None = None,
    aria_valuenow: int | float | None = None,
    aria_valuetext: str | None = None,
    auto_capitalize: AutoCapitalize | None = None,
    auto_correct: str | None = None,
    auto_focus: bool | None = None,
    auto_save: str | None = None,
    class_name: str | None = None,
    color: str | None = None,
    content: str | None = None,
    content_editable: ContentEditable | None = None,
    context_menu: str | None = None,
    datatype: str | None = None,
    default_checked: bool | None = None,
    default_value: str | int | float | list[str] | None = None,
    dir: str | None = None,
    download: str | bool | None = None,
    draggable: bool | None = None,
    enter_key_hint: EnterKeyHint | None = None,
    exportparts: str | None = None,
    hidden: bool | None = None,
    href: str | None = None,
    href_lang: str | None = None,
    id: str | None = None,
    inert: bool | None = None,
    inlist: str | None = None,
    input_mode: InputMode | None = None,
    is_: str | None = None,
    item_id: str | None = None,
    item_prop: str | None = None,
    item_ref: str | None = None,
    item_scope: bool | None = None,
    item_type: str | None = None,
    lang: str | None = None,
    media: str | None = None,
    nonce: str | None = None,
    part: str | None = None,
    ping: str | None = None,
    popover: Popover | None = None,
    popover_target: str | None = None,
    popover_target_action: PopoverTargetAction | None = None,
    prefix: str | None = None,
    property: str | None = None,
    radio_group: str | None = None,
    referrer_policy: ReferrerPolicy | None = None,
    rel: str | None = None,
    resource: str | None = None,
    results: int | float | None = None,
    rev: str | None = None,
    role: Role | None = None,
    security: str | None = None,
    slot: str | None = None,
    spell_check: bool | None = None,
    style: StyleInput | None = None,
    suppress_content_editable_warning: bool | None = None,
    suppress_hydration_warning: bool | None = None,
    tab_index: int | float | None = None,
    target: Literal["_self", "_blank", "_parent", "_top"] | None = None,
    title: str | None = None,
    translate: Translate | None = None,
    type: str | None = None,
    typeof: str | None = None,
    unselectable: Unselectable | None = None,
    vocab: str | None = None,
    on_blur: FocusEventHandler | None = None,
    on_change: EventHandler | None = None,
    on_click: MouseEventHandler | None = None,
    on_context_menu: MouseEventHandler | None = None,
    on_double_click: MouseEventHandler | None = None,
    on_drag: DragEventHandler | None = None,
    on_drag_end: DragEventHandler | None = None,
    on_drag_enter: DragEventHandler | None = None,
    on_drag_leave: DragEventHandler | None = None,
    on_drag_over: DragEventHandler | None = None,
    on_drag_start: DragEventHandler | None = None,
    on_drop: DragEventHandler | None = None,
    on_focus: FocusEventHandler | None = None,
    on_input: InputEventHandler | None = None,
    on_key_down: KeyboardEventHandler | None = None,
    on_key_up: KeyboardEventHandler | None = None,
    on_mouse_down: MouseEventHandler | None = None,
    on_mouse_enter: MouseEventHandler | None = None,
    on_mouse_leave: MouseEventHandler | None = None,
    on_mouse_move: MouseEventHandler | None = None,
    on_mouse_out: MouseEventHandler | None = None,
    on_mouse_over: MouseEventHandler | None = None,
    on_mouse_up: MouseEventHandler | None = None,
    on_scroll: UIEventHandler | None = None,
    on_submit: SubmitEventHandler | None = None,
    on_wheel: WheelEventHandler | None = None,
    data: Mapping[str, DataValue] | None = None,
) -> HtmlContainerElement: ...


@html_element("a", is_container=True, name="A")
def _A(
    inner_text: str | None = None,
    /,
    *,
    about: str | None = None,
    access_key: str | None = None,
    aria_activedescendant: str | None = None,
    aria_atomic: bool | None = None,
    aria_autocomplete: AriaAutocomplete | None = None,
    aria_braillelabel: str | None = None,
    aria_brailleroledescription: str | None = None,
    aria_busy: bool | None = None,
    aria_checked: AriaChecked | None = None,
    aria_colcount: int | float | None = None,
    aria_colindex: int | float | None = None,
    aria_colindextext: str | None = None,
    aria_colspan: int | float | None = None,
    aria_controls: str | None = None,
    aria_current: AriaCurrent | None = None,
    aria_describedby: str | None = None,
    aria_description: str | None = None,
    aria_details: str | None = None,
    aria_disabled: bool | None = None,
    aria_dropeffect: AriaDropeffect | None = None,
    aria_errormessage: str | None = None,
    aria_expanded: bool | None = None,
    aria_flowto: str | None = None,
    aria_grabbed: bool | None = None,
    aria_haspopup: AriaHaspopup | None = None,
    aria_hidden: bool | None = None,
    aria_invalid: AriaInvalid | None = None,
    aria_keyshortcuts: str | None = None,
    aria_label: str | None = None,
    aria_labelledby: str | None = None,
    aria_level: int | float | None = None,
    aria_live: AriaLive | None = None,
    aria_modal: bool | None = None,
    aria_multiline: bool | None = None,
    aria_multiselectable: bool | None = None,
    aria_orientation: AriaOrientation | None = None,
    aria_owns: str | None = None,
    aria_placeholder: str | None = None,
    aria_posinset: int | float | None = None,
    aria_pressed: AriaPressed | None = None,
    aria_readonly: bool | None = None,
    aria_relevant: AriaRelevant | None = None,
    aria_required: bool | None = None,
    aria_roledescription: str | None = None,
    aria_rowcount: int | float | None = None,
    aria_rowindex: int | float | None = None,
    aria_rowindextext: str | None = None,
    aria_rowspan: int | float | None = None,
    aria_selected: bool | None = None,
    aria_setsize: int | float | None = None,
    aria_sort: AriaSort | None = None,
    aria_valuemax: int | float | None = None,
    aria_valuemin: int | float | None = None,
    aria_valuenow: int | float | None = None,
    aria_valuetext: str | None = None,
    auto_capitalize: AutoCapitalize | None = None,
    auto_correct: str | None = None,
    auto_focus: bool | None = None,
    auto_save: str | None = None,
    class_name: str | None = None,
    color: str | None = None,
    content: str | None = None,
    content_editable: ContentEditable | None = None,
    context_menu: str | None = None,
    datatype: str | None = None,
    default_checked: bool | None = None,
    default_value: str | int | float | list[str] | None = None,
    dir: str | None = None,
    download: str | bool | None = None,
    draggable: bool | None = None,
    enter_key_hint: EnterKeyHint | None = None,
    exportparts: str | None = None,
    hidden: bool | None = None,
    href: str | None = None,
    href_lang: str | None = None,
    id: str | None = None,
    inert: bool | None = None,
    inlist: str | None = None,
    input_mode: InputMode | None = None,
    is_: str | None = None,
    item_id: str | None = None,
    item_prop: str | None = None,
    item_ref: str | None = None,
    item_scope: bool | None = None,
    item_type: str | None = None,
    lang: str | None = None,
    media: str | None = None,
    nonce: str | None = None,
    part: str | None = None,
    ping: str | None = None,
    popover: Popover | None = None,
    popover_target: str | None = None,
    popover_target_action: PopoverTargetAction | None = None,
    prefix: str | None = None,
    property: str | None = None,
    radio_group: str | None = None,
    referrer_policy: ReferrerPolicy | None = None,
    rel: str | None = None,
    resource: str | None = None,
    results: int | float | None = None,
    rev: str | None = None,
    role: Role | None = None,
    security: str | None = None,
    slot: str | None = None,
    spell_check: bool | None = None,
    style: StyleInput | None = None,
    suppress_content_editable_warning: bool | None = None,
    suppress_hydration_warning: bool | None = None,
    tab_index: int | float | None = None,
    target: Literal["_self", "_blank", "_parent", "_top"] | None = None,
    title: str | None = None,
    translate: Translate | None = None,
    type: str | None = None,
    typeof: str | None = None,
    unselectable: Unselectable | None = None,
    vocab: str | None = None,
    on_blur: FocusEventHandler | None = None,
    on_change: EventHandler | None = None,
    on_click: MouseEventHandler | None = None,
    on_context_menu: MouseEventHandler | None = None,
    on_double_click: MouseEventHandler | None = None,
    on_drag: DragEventHandler | None = None,
    on_drag_end: DragEventHandler | None = None,
    on_drag_enter: DragEventHandler | None = None,
    on_drag_leave: DragEventHandler | None = None,
    on_drag_over: DragEventHandler | None = None,
    on_drag_start: DragEventHandler | None = None,
    on_drop: DragEventHandler | None = None,
    on_focus: FocusEventHandler | None = None,
    on_input: InputEventHandler | None = None,
    on_key_down: KeyboardEventHandler | None = None,
    on_key_up: KeyboardEventHandler | None = None,
    on_mouse_down: MouseEventHandler | None = None,
    on_mouse_enter: MouseEventHandler | None = None,
    on_mouse_leave: MouseEventHandler | None = None,
    on_mouse_move: MouseEventHandler | None = None,
    on_mouse_out: MouseEventHandler | None = None,
    on_mouse_over: MouseEventHandler | None = None,
    on_mouse_up: MouseEventHandler | None = None,
    on_scroll: UIEventHandler | None = None,
    on_submit: SubmitEventHandler | None = None,
    on_wheel: WheelEventHandler | None = None,
    data: Mapping[str, DataValue] | None = None,
) -> Element:
    """<a />"""
    ...
