"""Generated HTML forms runtime wrappers.

Internal codegen artifact for trellis.html.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements

Generated by html-codegen.
"""

from __future__ import annotations

from trellis.html._runtime_factory import create_html_element

__all__ = [
    "Button",
    "Datalist",
    "Fieldset",
    "Form",
    "Input",
    "Label",
    "Legend",
    "Meter",
    "Optgroup",
    "Option",
    "Output",
    "Progress",
    "Select",
    "Textarea",
]

Button = create_html_element(
    "button",
    component_name="Button",
    export_name="Button",
    is_container=True,
    doc="Generated wrapper for `<button>`.\n\nMaps to the standard HTML `<button>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button",
)
Datalist = create_html_element(
    "datalist",
    component_name="Datalist",
    export_name="Datalist",
    is_container=True,
    doc="Generated wrapper for `<datalist>`.\n\nMaps to the standard HTML `<datalist>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist",
)
Fieldset = create_html_element(
    "fieldset",
    component_name="Fieldset",
    export_name="Fieldset",
    is_container=True,
    doc="Generated wrapper for `<fieldset>`.\n\nMaps to the standard HTML `<fieldset>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset",
)
Form = create_html_element(
    "form",
    component_name="Form",
    export_name="Form",
    is_container=True,
    doc="Generated wrapper for `<form>`.\n\nMaps to the standard HTML `<form>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form",
)
Input = create_html_element(
    "input",
    component_name="Input",
    export_name="Input",
    doc="Generated wrapper for `<input>`.\n\nMaps to the standard HTML `<input>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input",
)
Label = create_html_element(
    "label",
    component_name="Label",
    export_name="Label",
    is_container=True,
    doc="Generated wrapper for `<label>`.\n\nMaps to the standard HTML `<label>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label",
)
Legend = create_html_element(
    "legend",
    component_name="Legend",
    export_name="Legend",
    is_container=True,
    doc="Generated wrapper for `<legend>`.\n\nMaps to the standard HTML `<legend>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend",
)
Meter = create_html_element(
    "meter",
    component_name="Meter",
    export_name="Meter",
    is_container=True,
    doc="Generated wrapper for `<meter>`.\n\nMaps to the standard HTML `<meter>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter",
)
Optgroup = create_html_element(
    "optgroup",
    component_name="Optgroup",
    export_name="Optgroup",
    is_container=True,
    doc="Generated wrapper for `<optgroup>`.\n\nMaps to the standard HTML `<optgroup>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup",
)
Option = create_html_element(
    "option",
    component_name="Option",
    export_name="Option",
    doc="Generated wrapper for `<option>`.\n\nMaps to the standard HTML `<option>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option",
)
Output = create_html_element(
    "output",
    component_name="Output",
    export_name="Output",
    is_container=True,
    doc="Generated wrapper for `<output>`.\n\nMaps to the standard HTML `<output>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output",
)
Progress = create_html_element(
    "progress",
    component_name="Progress",
    export_name="Progress",
    is_container=True,
    doc="Generated wrapper for `<progress>`.\n\nMaps to the standard HTML `<progress>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress",
)
Select = create_html_element(
    "select",
    component_name="Select",
    export_name="Select",
    is_container=True,
    doc="Generated wrapper for `<select>`.\n\nMaps to the standard HTML `<select>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select",
)
Textarea = create_html_element(
    "textarea",
    component_name="Textarea",
    export_name="Textarea",
    doc="Generated wrapper for `<textarea>`.\n\nMaps to the standard HTML `<textarea>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea",
)
