"""Generated HTML document metadata runtime wrappers.

Internal codegen artifact for trellis.html.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements

Generated by html-codegen.
"""

from __future__ import annotations

from trellis.html._runtime_factory import create_html_element

__all__ = [
    "Base",
    "Body",
    "Head",
    "Html",
    "Link",
    "Meta",
    "StyleTag",
    "Title",
]

Base = create_html_element(
    "base",
    component_name="Base",
    export_name="Base",
    doc="Generated wrapper for `<base>`.\n\nMaps to the standard HTML `<base>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base",
)
Body = create_html_element(
    "body",
    component_name="Body",
    export_name="Body",
    is_container=True,
    doc="Generated wrapper for `<body>`.\n\nMaps to the standard HTML `<body>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body",
)
Head = create_html_element(
    "head",
    component_name="Head",
    export_name="Head",
    is_container=True,
    doc="Generated wrapper for `<head>`.\n\nMaps to the standard HTML `<head>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head",
)
Html = create_html_element(
    "html",
    component_name="Html",
    export_name="Html",
    is_container=True,
    doc="Generated wrapper for `<html>`.\n\nMaps to the standard HTML `<html>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html",
)
Link = create_html_element(
    "link",
    component_name="Link",
    export_name="Link",
    doc="Generated wrapper for `<link>`.\n\nMaps to the standard HTML `<link>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link",
)
Meta = create_html_element(
    "meta",
    component_name="Meta",
    export_name="Meta",
    doc="Generated wrapper for `<meta>`.\n\nMaps to the standard HTML `<meta>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta",
)
StyleTag = create_html_element(
    "style",
    component_name="StyleTag",
    export_name="StyleTag",
    doc="Generated wrapper for `<style>`.\n\nMaps to the standard HTML `<style>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style",
)
Title = create_html_element(
    "title",
    component_name="Title",
    export_name="Title",
    doc="Generated wrapper for `<title>`.\n\nMaps to the standard HTML `<title>` element.\nReference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title",
)
