import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import examplesSidebar from './src/generated-examples-sidebar.json';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {type: 'doc', id: 'intro'},
    {type: 'doc', id: 'quickstart'},
    {type: 'doc', id: 'concepts'},
    {type: 'doc', id: 'building-uis'},
    {type: 'doc', id: 'patterns'},
    {type: 'doc', id: 'theming'},
    {
      type: 'category',
      label: 'Examples',
      items: examplesSidebar,
    },
    {
      type: 'category',
      label: 'Design',
      items: [{type: 'autogenerated', dirName: 'design'}],
    },
    {
      type: 'category',
      label: 'API',
      items: [{type: 'autogenerated', dirName: 'api/reference/trellis'}],
    },
  ],
};

export default sidebars;
