import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import examplesSidebar from './src/generated-examples-sidebar.json';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {
      type: 'category',
      label: 'Examples',
      items: examplesSidebar,
    },
  ],
};

export default sidebars;
