"""Workspace utilities and code generation for bundle building.

Provides workspace management and generates the _registry.ts wiring file
that connects all registered modules together.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from jinja2 import Template

from .registry import CollectedModules, ExportKind
from .utils import find_project_root

# Template for generating _registry.ts
_REGISTRY_TS_TEMPLATE = Template(
    """\
// Auto-generated by trellis bundler
{% if components %}

import { registerWidget } from "@trellis/trellis-core/widgets/index";
{% endif %}
{% if initializers %}
{% for module, source in initializers %}
import "@trellis/{{ module }}/{{ source }}";
{% endfor %}
{% endif %}
{% if stylesheets %}
{% for module, source in stylesheets %}
import "@trellis/{{ module }}/{{ source }}";
{% endfor %}
{% endif %}
{% if components %}
{% for name, module, source in components %}
import { {{ name }} } from "@trellis/{{ module }}/{{ source }}";
{% endfor %}
{% endif %}
{% if functions %}
{% for name, module, source in functions %}
import { {{ name }} } from "@trellis/{{ module }}/{{ source }}";
{% endfor %}

export { {{ functions | map(attribute=0) | join(', ') }} };
{% endif %}

export function initRegistry(): void {
{% for name, module, source in components %}
  registerWidget("{{ name }}", {{ name }});
{% endfor %}
}
"""
)


def get_project_hash(entry_point: Path) -> str:
    """Get a hash identifying a project based on its entry point path.

    Args:
        entry_point: Path to the project's entry point file

    Returns:
        A short hash string identifying this project
    """
    path_str = str(entry_point.resolve())
    return hashlib.sha256(path_str.encode()).hexdigest()[:16]


def get_project_workspace(entry_point: Path) -> Path:
    """Get the workspace directory for a project.

    The workspace is in a .trellis directory at the project root,
    identified by a hash of the entry point path. This ensures each
    entry point gets its own isolated build workspace.

    Args:
        entry_point: Path to the project's entry point file

    Returns:
        Path to the project's workspace directory (created if needed)
    """
    project_root = find_project_root(entry_point)
    project_hash = get_project_hash(entry_point)
    workspace = project_root / ".trellis" / project_hash
    workspace.mkdir(parents=True, exist_ok=True)
    return workspace


def write_registry_ts(workspace: Path, collected: CollectedModules) -> Path:
    """Generate and write the _registry.ts wiring file.

    Creates the workspace directory if needed and writes _registry.ts.

    Args:
        workspace: Workspace directory to write to
        collected: Collected modules with exports to register

    Returns:
        Path to the written _registry.ts file
    """
    workspace.mkdir(parents=True, exist_ok=True)
    registry_path = workspace / "_registry.ts"
    registry_code = generate_registry_ts(collected)
    registry_path.write_text(registry_code)
    return registry_path


def generate_registry_ts(collected: CollectedModules) -> str:
    """Generate the _registry.ts wiring file.

    This file:
    - Imports all component exports and registers them via registerWidget()
    - Imports all initializer exports for their side effects
    - Re-exports all function exports
    - Exports an initRegistry() function that registers all components

    Args:
        collected: Collected modules

    Returns:
        TypeScript code for _registry.ts
    """
    components: list[tuple[str, str, str]] = []  # (name, module, source)
    functions: list[tuple[str, str, str]] = []  # (name, module, source)
    initializers: list[tuple[str, str]] = []  # (module, source)
    stylesheets: list[tuple[str, str]] = []  # (module, source)

    for module in collected.modules:
        for export in module.exports:
            # Remove .tsx/.ts extension for import path (but keep .css)
            source_path = export.source
            if source_path.endswith(".tsx"):
                source_path = source_path[:-4]
            elif source_path.endswith(".ts"):
                source_path = source_path[:-3]

            if export.kind == ExportKind.COMPONENT:
                components.append((export.name, module.name, source_path))
            elif export.kind == ExportKind.FUNCTION:
                functions.append((export.name, module.name, source_path))
            elif export.kind == ExportKind.INITIALIZER:
                initializers.append((module.name, source_path))
            elif export.kind == ExportKind.STYLESHEET:
                stylesheets.append((module.name, export.source))

    return _REGISTRY_TS_TEMPLATE.render(
        components=components,
        functions=functions,
        initializers=initializers,
        stylesheets=stylesheets,
    )
